const localLabels: any = {
  // IBAN -----------------------
  AU: {
    isIban: true,
    accountLengthMin: 20,
    accountLengthMax: 20,
    routingLabel: 'IBAN',
    routingTooltip: null,
  },
  BE: {
    isIban: true,
    accountLengthMin: 16,
    accountLengthMax: 16,
    routingLabel: 'IBAN',
    routingTooltip: null,
  },
  CH: {
    isIban: true,
    accountLengthMin: 21,
    accountLengthMax: 21,
    routingLabel: 'IBAN',
    routingTooltip: null,
  },
  DE: {
    isIban: true,
    accountLengthMin: 22,
    accountLengthMax: 22,
    routingLabel: 'IBAN',
    routingTooltip: null,
  },
  DK: {
    isIban: true,
    accountLengthMin: 18,
    accountLengthMax: 18,
    routingLabel: 'IBAN',
    routingTooltip: null,
  },
  ES: {
    isIban: true,
    accountLengthMin: 24,
    accountLengthMax: 24,
    routingLabel: 'IBAN',
    routingTooltip: null,
  },
  FI: {
    isIban: true,
    accountLengthMin: 18,
    accountLengthMax: 18,
    routingLabel: 'IBAN',
    routingTooltip: null,
  },
  FR: {
    isIban: true,
    accountLengthMin: 27,
    accountLengthMax: 27,
    routingLabel: 'IBAN',
    routingTooltip: null,
  },
  IE: {
    isIban: true,
    accountLengthMin: 22,
    accountLengthMax: 22,
    routingLabel: 'IBAN',
    routingTooltip: null,
  },
  IT: {
    isIban: true,
    accountLengthMin: 27,
    accountLengthMax: 27,
    routingLabel: 'IBAN',
    routingTooltip: null,
  },
  LU: {
    isIban: true,
    accountLengthMin: 20,
    accountLengthMax: 20,
    routingLabel: 'IBAN',
    routingTooltip: null,
  },
  NL: {
    isIban: true,
    accountLengthMin: 18,
    accountLengthMax: 18,
    routingLabel: 'IBAN',
    routingTooltip: null,
  },
  NO: {
    isIban: true,
    accountLengthMin: 15,
    accountLengthMax: 15,
    routingLabel: 'IBAN',
    routingTooltip: null,
  },
  PT: {
    isIban: true,
    accountLengthMin: 25,
    accountLengthMax: 25,
    routingLabel: 'IBAN',
    routingTooltip: null,
  },
  SE: {
    isIban: true,
    accountLengthMin: 24,
    accountLengthMax: 24,
    routingLabel: 'IBAN',
    routingTooltip: null,
  },
  // NOT IBAN -----------------------
  AT: {
    isIban: false,
    accountLengthMin: null,
    routingLabel: 'BSB',
    routingTooltip: 'Enter your 6-digit BSB code',
    routingLength: 8,
  },
  CA: {
    isIban: false,
    accountLengthMin: null,
    routingLabel: null,
    routingTooltip: 'Your routing number should by 8-digits long and',
  },
  GB: {
    isIban: false,
    accountLengthMin: null,
    routingLabel: null,
    routingTooltip: null,
  },
  HK: {
    isIban: false,
    accountLengthMin: null,
    routingLabel: null,
    routingTooltip: null,
  },
  NZ: {
    isIban: false,
    accountLengthMin: null,
    routingLabel: null,
    routingTooltip: null,
  },
  SG: {
    isIban: false,
    accountLengthMin: null,
    routingLabel: null,
    routingTooltip: null,
  },
  US: {
    isIban: false,
    accountLengthMin: null,
    routingLabel: null,
    routingTooltip: null,
  },
};
export default localLabels;
