rm -rf dist;
ng build;
say 'done';
cd dist;
mv browser static;
mv static/en/index.html .;
mv static/en/manifest.webmanifest .;
mv static/en/ngsw.json .;
mv static/en/ngsw-worker.js .;
mv static/en/worker-basic.min.js .;
mv static/en/safety-worker.js .;
http-server -p 8082 -c-1 .;
