import { MultiTenantDomain } from '../../../../../../graphql/generated.engine';

/**
 * The MultiTenantDomain type, but without the tenantId
 */
export type ReturnedMultiTenantDomain = Omit<MultiTenantDomain, 'tenantId'>;

/**
 * These are the different ways we present the current domain status.
 */
export enum MultiTenantDomainStatus {
  AUTOGENERATED,
  ACTIVE,
  PENDING,
  FAILED,
}
