import { MultiTenantDomain } from '../../../../../../graphql/generated.engine';

/**
 * tenantId is not returned
 */
export type ReturnedMultiTenantDomain = Omit<MultiTenantDomain, 'tenantId'>;

/**
 * These are the different ways we present the current domain.
 */
export enum MultiTenantDomainStatus {
  AUTOGENERATED,
  ACTIVE,
  PENDING,
  FAILED,
}
