import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';
import { FeedsService } from '../../../../common/services/feeds.service';

export type OnboardingPanelSuggestionsType = 'channels' | 'groups';

/**
 * Service for handling suggestions panel.
 */
@Injectable({ providedIn: 'root' })
export class OnboardingV3SuggestionsPanelService {
  /**
   * Holds if in progress.
   */
  public readonly inProgress$: BehaviorSubject<boolean> = new BehaviorSubject<
    boolean
  >(false);

  /**
   * Holds observable of suggestions once feeds service has been called.
   * @returns { BehaviorSubject<any> }
   */
  get suggestions$(): BehaviorSubject<any> {
    // TODO: Remove stub
    // return this.feeds.rawFeed;
    return new BehaviorSubject<any>(mockResponse.entities);
  }

  constructor(private feeds: FeedsService) {}

  /**
   * Load suggestions from server.
   * @returns { Promise<void> }
   */
  public async load(
    type: OnboardingPanelSuggestionsType = 'channels'
  ): Promise<void> {
    // TODO: BH: Implement refresh?
    // if (refresh) {
    //   this.feedsService.clear();
    // }

    this.inProgress$.next(true);

    try {
      const hashtags = '';
      const period = '1y';
      const all = '';
      const query = '';
      const nsfw = [];

      await this.feeds
        .setEndpoint(`api/v2/feeds/global/top/${type}`)
        .setParams({
          hashtags,
          period,
          all,
          query,
          nsfw,
        })
        .setLimit(12)
        .setExportUserCounts(true)
        .fetch();
    } catch (e) {
      console.error('SortedComponent', e);
    }

    this.inProgress$.next(false);
  }
}

//TODO: REMOVE
const mockResponse = {
  status: 'success',

  //TODO: Remove stub, test with groups and swap for actual endpoint response
  entities: [
    {
      guid: '835201392342736910',
      owner_guid: '835201392342736910',
      timestamp: null,
      urn: 'urn:user:835201392342736910',
      entity: {
        guid: '835201392342736910',
        type: 'user',
        subtype: false,
        time_created: '1524503529',
        time_updated: false,
        container_guid: '0',
        owner_guid: '0',
        site_guid: false,
        access_id: '2',
        tags: ['all', 'blockchain', 'minds', 'comedy', 'gaming', 'memes'],
        nsfw: [],
        nsfw_lock: [],
        allow_comments: false,
        name: 'TrumpWon!',
        username: 'Willieleev1971',
        language: 'en',
        icontime: '1605978692',
        legacy_guid: false,
        featured_id: false,
        banned: 'no',
        ban_reason: false,
        website: '',
        briefdescription:
          'Please do not send me tokens,  visiting my channel is thanks enough if you come looking for tokens, you are looking in the wrong place, minds.com is no longer doubling them, so I am not getting as many to pass out, sorry',
        gender: '',
        city: '',
        merchant: {
          service: 'stripe',
          id: 'acct_1HgWyeHtVf7f3pTH',
        },
        boostProPlus: false,
        fb: false,
        mature: 0,
        monetized: '',
        signup_method: false,
        social_profiles: [],
        feature_flags: false,
        programs: [],
        plus: true,
        hashtags: false,
        verified: true,
        founder: false,
        disabled_boost: false,
        boost_autorotate: false,
        categories: [],
        wire_rewards: null,
        pinned_posts: [
          '1145134419298967552',
          '1164412633664000000',
          '1168604610077609984',
          '1173490349343305728',
          '1177731214468993024',
          '1182238648678391808',
          '1182518253197488128',
          '1183334446375899136',
          '1186436173823528960',
        ],
        is_mature: false,
        mature_lock: false,
        last_accepted_tos: 1558597098,
        opted_in_hashtags: 2,
        last_avatar_upload: '1561466242',
        canary: true,
        theme: 'light',
        toaster_notifications: true,
        mode: 0,
        btc_address: '',
        surge_token:
          'eyJzZXJ2aWNlIjoiZ29vZ2xlIiwidG9rZW4iOiJjZzhDQ2E3TWhvTTpBUEE5MWJIMko1eW13cmZ6VDU0Xzk5Y1BhODhYcldGTUJPeUt6by1nQkNfdzNQNkstVVlvVERHODhSaWttaXBfYk1WR1B2d1BfaThUenpQcEk0ZGJ1TGFjYXBYWUJkdWRPOEtyVlhtdVhHMjJ6eEd0VFVCVVJiQTd0OERzeTNCTnpBNk9Sd2lPVGM2YyJ9',
        hide_share_buttons: false,
        allow_unsubscribed_contact: false,
        dismissed_widgets: ['discovery-disclaimer-2020'],
        chat: true,
        urn: 'urn:user:835201392342736910',
        subscribed: 0,
        subscriber: 0,
        subscribers_count: 12095,
        subscriptions_count: 4999,
        impressions: 20489300,
        boost_rating: 1,
        pro: true,
        pro_published: false,
        rewards: true,
        p2p_media_enabled: false,
        is_admin: false,
        onchain_booster: 0,
        email_confirmed: true,
        eth_wallet: '0xA5b27721394DA00A276ad367BBc49a837332762a',
        rating: 1,
        disable_autoplay_videos: false,
        yt_channels: [],
      },
    },
    {
      guid: '874895823303876625',
      owner_guid: '874895823303876625',
      timestamp: null,
      urn: 'urn:user:874895823303876625',
      entity: {
        guid: '874895823303876625',
        type: 'user',
        subtype: false,
        time_created: '1533967418',
        time_updated: false,
        container_guid: '0',
        owner_guid: '0',
        site_guid: false,
        access_id: '2',
        tags: [],
        nsfw: [],
        nsfw_lock: [],
        allow_comments: false,
        name: 'SGZimmer',
        username: 'SGZimmer',
        language: 'en',
        icontime: '1576646854',
        legacy_guid: false,
        featured_id: false,
        banned: 'no',
        ban_reason: false,
        website: '',
        briefdescription:
          "Writer, filmmaker, broadcaster ( Star Chamber Show, The Creative's Cauldron). Imaginarium Convention & Seventh Star Press. #FreeThinker #FreeSpeech #Freedom",
        gender: '',
        city: 'Lexington',
        merchant: false,
        boostProPlus: false,
        fb: false,
        mature: 0,
        monetized: '',
        signup_method: false,
        social_profiles: [
          {
            key: 'facebook',
            value: 'https://www.facebook.com/stephenzimmer7',
          },
          {
            key: 'twitter',
            value: 'https://www.twitter.com/sgzimmer',
          },
          {
            key: 'instagram',
            value: 'https://www.instagram.com/stephenzimmer7',
          },
          {
            key: 'other',
            value: 'https://www.gab.ai/sgzimmer',
          },
        ],
        feature_flags: false,
        programs: [],
        plus: false,
        hashtags: false,
        verified: false,
        founder: false,
        disabled_boost: false,
        boost_autorotate: true,
        categories: [],
        wire_rewards: null,
        pinned_posts: [],
        is_mature: false,
        mature_lock: false,
        last_accepted_tos: 1558597098,
        opted_in_hashtags: 0,
        last_avatar_upload: '0',
        canary: false,
        theme: false,
        toaster_notifications: true,
        mode: 0,
        btc_address: '',
        surge_token: '',
        hide_share_buttons: false,
        allow_unsubscribed_contact: false,
        dismissed_widgets: [],
        urn: 'urn:user:874895823303876625',
        subscribed: 0,
        subscriber: 0,
        subscribers_count: 8,
        subscriptions_count: 9,
        impressions: 637,
        boost_rating: 1,
        pro: false,
        pro_published: false,
        rewards: false,
        p2p_media_enabled: false,
        is_admin: false,
        onchain_booster: 0,
        email_confirmed: true,
        eth_wallet: '',
        rating: 1,
        disable_autoplay_videos: false,
        yt_channels: [],
      },
    },
    {
      guid: '741713837215981571',
      owner_guid: '741713837215981571',
      timestamp: null,
      urn: 'urn:user:741713837215981571',
      entity: {
        guid: '741713837215981571',
        type: 'user',
        subtype: '',
        time_created: '1502214359',
        time_updated: '',
        container_guid: '0',
        owner_guid: '0',
        site_guid: '',
        access_id: '2',
        tags: ['news', 'Politics', 'journalism', 'Nationalism', 'Nationalist'],
        nsfw: [],
        nsfw_lock: [],
        allow_comments: false,
        name: 'K23 NEWS',
        username: 'Kitch23',
        language: 'en',
        icontime: '1605750302',
        legacy_guid: '',
        featured_id: '',
        banned: 'no',
        ban_reason: false,
        website: '',
        briefdescription:
          'News, analysis and opinions from the perspective of Classical Liberals, Libertarians, small c Conservatives and big C Conservatives.\n\nConservative is the new punk. Welcome to the counterculture. \n\nOnline from 5:30 AM to 5:30 PM (PST) Monday to Friday \n\nI post satire between 5:00 PM and 5:30 PM (PST)\n\nThe opinions expressed in the videos, news articles and commentary do not necessarily reflect those of K23 NEWS \n\nK23NEWS.com\n\nKitch23@ProtonMail.com\n\nParler.com/profile/kitch\n\nhttps://teespring.com/stores/k23-news\n\nhttps://www.subscribestar.com/k23-news',
        gender: '',
        city: 'Thousand Oaks, California ',
        merchant: {
          service: 'stripe',
          id: 'acct_1FyiJOHZjdFQxWvd',
        },
        boostProPlus: '',
        fb: '',
        mature: 0,
        monetized: '',
        signup_method: '',
        social_profiles: [],
        feature_flags: null,
        programs: [],
        plus: true,
        hashtags: '',
        verified: true,
        founder: false,
        disabled_boost: false,
        boost_autorotate: true,
        categories: [],
        wire_rewards: null,
        pinned_posts: [
          '1048388589925150720',
          '1079110066037846016',
          '1113874772454293504',
          '1130499156666175488',
          '1113867871154823168',
          '1132311350067343360',
          '1159861401986674688',
        ],
        is_mature: false,
        mature_lock: false,
        last_accepted_tos: 1558597098,
        opted_in_hashtags: -6,
        last_avatar_upload: '1564459648',
        canary: false,
        theme: 'dark',
        onchain_booster: 1592012966,
        toaster_notifications: true,
        mode: 0,
        btc_address: '3F1KsRjfod3aGUKrUoT13iH7wmRK7JQP3S',
        surge_token:
          'eyJzZXJ2aWNlIjoiZ29vZ2xlIiwidG9rZW4iOiJmeFZES2Izai10czpBUEE5MWJGVWxHdUxiS1FocE4wR3hvajZLdzRmM3g3QjVsVl9HaVlOWmtBczltSWxTZjhWelZXdXBkQUhfNGpEb1RYQUJIdDBSdnA5b2VuVFZDN0JrNXlrbGQ3TUwtamRocDd0Q1VqaXBFbERvakxWb1lzYW1RMFlsdnZieUtjbHhMZG96OC1QamZ5WSJ9',
        hide_share_buttons: false,
        allow_unsubscribed_contact: false,
        dismissed_widgets: ['discovery-disclaimer-2020'],
        chat: true,
        urn: 'urn:user:741713837215981571',
        subscribed: false,
        subscriber: false,
        subscribers_count: 9784,
        subscriptions_count: 128,
        impressions: 21252042,
        boost_rating: 2,
        pro: true,
        pro_published: true,
        rewards: true,
        p2p_media_enabled: false,
        is_admin: false,
        email_confirmed: true,
        eth_wallet: '0x5069F53C1daD1adB9bef885Da417c677dEcbB1A5',
        rating: 1,
        disable_autoplay_videos: false,
        yt_channels: [],
      },
    },
    {
      guid: '940591527099375618',
      owner_guid: '940591527099375618',
      timestamp: null,
      urn: 'urn:user:940591527099375618',
      entity: {
        guid: '940591527099375618',
        type: 'user',
        subtype: false,
        time_created: '1549630495',
        time_updated: false,
        container_guid: '0',
        owner_guid: '0',
        site_guid: false,
        access_id: '2',
        tags: ['journalism', 'politics', 'Justice', 'terrorism', 'Algeria'],
        nsfw: [],
        nsfw_lock: [],
        allow_comments: false,
        name: 'Moh35',
        username: 'moh35',
        language: 'en',
        icontime: '1605552628',
        legacy_guid: false,
        featured_id: false,
        banned: 'no',
        ban_reason: false,
        website: '',
        briefdescription:
          'Whistle blower, persecuted by the French state sponsored terrorism networks after my revelations , investigations in Reims/Charleville-Mézières, on the Charlie Hebdo false flag attacks.\n\nbitcoin wallet:\n\n31yiaRgbdKhJ993pAQeMQ8YWuSkSVALXRu\n',
        gender: '',
        city: 'Charleville-Mézières',
        merchant: false,
        boostProPlus: false,
        fb: false,
        mature: 1,
        monetized: '',
        signup_method: false,
        social_profiles: [
          {
            key: 'twitter',
            value: 'https://twitter.com/NiklafrO?s=09',
          },
          {
            key: 'youtube_channel',
            value: 'https://www.youtube.com/channel/UCirj5KBUJMhoLws_i3OxI6A',
          },
        ],
        feature_flags: false,
        programs: [],
        plus: false,
        hashtags: false,
        verified: false,
        founder: false,
        disabled_boost: false,
        boost_autorotate: true,
        categories: [],
        wire_rewards: {
          description: '',
          rewards: {
            points: [],
            money: [],
            tokens: [],
          },
        },
        pinned_posts: ['1077273614952792064', '1064527420570619904'],
        is_mature: false,
        mature_lock: false,
        last_accepted_tos: 1558597098,
        opted_in_hashtags: 5,
        last_avatar_upload: '0',
        canary: false,
        theme: 'light',
        toaster_notifications: true,
        mode: 0,
        btc_address: '',
        surge_token:
          'eyJzZXJ2aWNlIjoiZ29vZ2xlIiwidG9rZW4iOiJkTmFuNmpDMTBGdzpBUEE5MWJIYXVCWXQxbmotYmV3NUhxRmxQMzhybnNRLWFMZUxSNl9MbmhIR1gzRjNpSUJTT0dqQlp4ajJPd2FiNjBadnE5emZjVDRVenluV3R2VFZXTkVlZk5udnR5MHlSVzhFWlFidnZZVEtfdW4xMHU1NnR2MHJwSWpwejlPU3ZGY1RFTGRyWnptRSJ9',
        hide_share_buttons: false,
        allow_unsubscribed_contact: false,
        dismissed_widgets: ['discovery-disclaimer-2020'],
        chat: true,
        urn: 'urn:user:940591527099375618',
        subscribed: false,
        subscriber: false,
        subscribers_count: 85,
        subscriptions_count: 15,
        impressions: 44097,
        boost_rating: 2,
        pro: false,
        pro_published: false,
        rewards: true,
        p2p_media_enabled: false,
        is_admin: false,
        onchain_booster: 0,
        email_confirmed: true,
        eth_wallet: '0x3b062d0B7eA1F3B8611c4b9DeDf56105B4053317',
        rating: 1,
        disable_autoplay_videos: false,
        yt_channels: [],
      },
    },
    {
      guid: '835845331525574672',
      owner_guid: '835845331525574672',
      timestamp: null,
      urn: 'urn:user:835845331525574672',
      entity: {
        guid: '835845331525574672',
        type: 'user',
        subtype: false,
        time_created: '1524657056',
        time_updated: false,
        container_guid: '0',
        owner_guid: '0',
        site_guid: false,
        access_id: '2',
        tags: [],
        nsfw: [],
        nsfw_lock: [],
        allow_comments: false,
        name: 'DzienDobryBialystok',
        username: 'DzienDobryBialystok',
        language: 'pl',
        icontime: '1587932810',
        legacy_guid: false,
        featured_id: false,
        banned: 'no',
        ban_reason: false,
        website: '',
        briefdescription:
          'Wiadomości lokalne, wiadomości z kraju i ze świata\n',
        gender: '',
        city: 'Bialystok',
        merchant: false,
        boostProPlus: false,
        fb: false,
        mature: 0,
        monetized: '',
        signup_method: false,
        social_profiles: [
          {
            key: 'facebook',
            value: 'https://www.facebook.com/dziendobrybialystok/',
          },
          {
            key: 'other',
            value: 'https://ddb24.pl/',
          },
          {
            key: 'twitter',
            value: 'https://twitter.com/DDBialystok',
          },
        ],
        feature_flags: false,
        programs: [],
        plus: true,
        hashtags: false,
        verified: true,
        founder: false,
        disabled_boost: false,
        boost_autorotate: true,
        categories: [],
        wire_rewards: null,
        pinned_posts: ['994546120426577920'],
        is_mature: false,
        mature_lock: false,
        last_accepted_tos: 1558597098,
        opted_in_hashtags: 4,
        last_avatar_upload: '0',
        canary: false,
        theme: 'dark',
        toaster_notifications: true,
        mode: 0,
        btc_address: '',
        surge_token:
          'eyJzZXJ2aWNlIjoiZ29vZ2xlIiwidG9rZW4iOiJlS3FKYTE5YWJoZzpBUEE5MWJIWlp1OUJLQV9OOXBoNmFXSkFQcEQtRkpuRkdKcXNDOGdjcVRVMVVwUkw3N0NXQi1oaGNKTlQ3RzN4N0ptUTVqQnhtWDU4Z0N4TV91N05KMThSTEtwRXF4OUpzczhBWnNWc1Q0SnE0N1U5T2FyVUExOGFmaDM3UGxGeUR0VTRfS056VXB2XyJ9',
        hide_share_buttons: false,
        allow_unsubscribed_contact: false,
        dismissed_widgets: [],
        chat: true,
        urn: 'urn:user:835845331525574672',
        subscribed: false,
        subscriber: false,
        subscribers_count: 541,
        subscriptions_count: 322,
        impressions: 231132,
        boost_rating: 2,
        pro: false,
        pro_published: false,
        rewards: true,
        p2p_media_enabled: false,
        is_admin: false,
        onchain_booster: 0,
        email_confirmed: true,
        eth_wallet: '',
        rating: 1,
        disable_autoplay_videos: false,
        yt_channels: [],
      },
    },
    {
      guid: '832310054785916947',
      owner_guid: '832310054785916947',
      timestamp: null,
      urn: 'urn:user:832310054785916947',
      entity: {
        guid: '832310054785916947',
        type: 'user',
        subtype: false,
        time_created: '1523814180',
        time_updated: false,
        container_guid: '0',
        owner_guid: '0',
        site_guid: false,
        access_id: '2',
        tags: [],
        nsfw: [],
        nsfw_lock: [],
        allow_comments: false,
        name:
          'Phynster - Politics, the entertainment division of the US Military Industrial Complex - Zappa',
        username: 'Phynster',
        language: 'en',
        icontime: '1574167706',
        legacy_guid: false,
        featured_id: false,
        banned: 'no',
        ban_reason: false,
        website: '',
        briefdescription: 'Observation',
        gender: '',
        city: 'Climax',
        merchant: {
          exclusive: {
            background: 0,
            intro: '',
          },
        },
        boostProPlus: '',
        fb: [],
        mature: 1,
        monetized: '',
        signup_method: false,
        social_profiles: [],
        feature_flags: false,
        programs: [],
        plus: true,
        hashtags: false,
        verified: true,
        founder: false,
        disabled_boost: false,
        boost_autorotate: true,
        categories: [
          'politics',
          'health',
          'history',
          'music',
          'news',
          'technology',
        ],
        wire_rewards: null,
        pinned_posts: [
          '1187080923390902272',
          '1187084793854779392',
          '1187122354066755584',
        ],
        is_mature: false,
        mature_lock: false,
        last_accepted_tos: 1558597098,
        opted_in_hashtags: 15,
        last_avatar_upload: '1555684975',
        canary: false,
        theme: 'dark',
        toaster_notifications: false,
        mode: 0,
        btc_address: '0xc633Bc08DF0dd205556434b276076c6f31FEa01d',
        surge_token:
          'eyJzZXJ2aWNlIjoiZ29vZ2xlIiwidG9rZW4iOiJjdjhULXFCT2VQVTpBUEE5MWJGWXJMMnRRajVFdFlHMGxnWmRxbEFBWk1RNWVyNVFyd0ZsaWM2UU1iLWFhbHZlTjR2ODFrOGVlVy1PVUZEWGtiWUh6VnNQX0k5YU5GVldQb3NSbWpSYkdSQUlLTXB4dTFDbWVrUmVPOE9YYmw2OXI5bXpZa0tFTml5c1RPamtkRHNYR2x1VSJ9',
        hide_share_buttons: true,
        allow_unsubscribed_contact: false,
        dismissed_widgets: ['discovery-disclaimer-2020'],
        chat: true,
        urn: 'urn:user:832310054785916947',
        subscribed: false,
        subscriber: false,
        subscribers_count: 2491,
        subscriptions_count: 285,
        impressions: 2646253,
        boost_rating: 2,
        pro: false,
        pro_published: false,
        rewards: true,
        p2p_media_enabled: true,
        is_admin: false,
        onchain_booster: 0,
        email_confirmed: true,
        eth_wallet: '0xc633bc08df0dd205556434b276076c6f31fea01d',
        rating: 1,
        disable_autoplay_videos: true,
        yt_channels: [],
      },
    },
    {
      guid: '590659589624569870',
      owner_guid: '590659589624569870',
      timestamp: null,
      urn: 'urn:user:590659589624569870',
      entity: {
        guid: '590659589624569870',
        type: 'user',
        subtype: false,
        time_created: '1466200220',
        time_updated: false,
        container_guid: '0',
        owner_guid: '0',
        site_guid: false,
        access_id: '2',
        tags: [],
        nsfw: [],
        nsfw_lock: [],
        allow_comments: false,
        name: 'AquariusNL',
        username: 'AquariusNL',
        language: 'en',
        icontime: '1590407730',
        legacy_guid: false,
        featured_id: false,
        banned: 'no',
        ban_reason: false,
        website: '',
        briefdescription: '',
        gender: 'male',
        city: '',
        merchant: false,
        boostProPlus: false,
        fb: false,
        mature: 1,
        monetized: false,
        signup_method: false,
        social_profiles: [],
        feature_flags: false,
        programs: [],
        plus: false,
        hashtags: false,
        verified: false,
        founder: false,
        disabled_boost: false,
        boost_autorotate: true,
        categories: [],
        wire_rewards: null,
        pinned_posts: ['1089317522257788928'],
        is_mature: false,
        mature_lock: false,
        last_accepted_tos: 1558597098,
        opted_in_hashtags: 0,
        last_avatar_upload: '0',
        canary: false,
        theme: 'light',
        toaster_notifications: true,
        mode: 0,
        btc_address: '',
        surge_token: '',
        hide_share_buttons: true,
        allow_unsubscribed_contact: false,
        dismissed_widgets: [],
        chat: true,
        urn: 'urn:user:590659589624569870',
        subscribed: false,
        subscriber: false,
        subscribers_count: 623,
        subscriptions_count: 304,
        impressions: 467392,
        boost_rating: 2,
        pro: false,
        pro_published: false,
        rewards: false,
        p2p_media_enabled: false,
        is_admin: false,
        onchain_booster: 0,
        email_confirmed: true,
        eth_wallet: '',
        rating: 1,
        disable_autoplay_videos: false,
        yt_channels: [],
      },
    },
    {
      guid: '929055781758705675',
      owner_guid: '929055781758705675',
      timestamp: null,
      urn: 'urn:user:929055781758705675',
      entity: {
        guid: '929055781758705675',
        type: 'user',
        subtype: false,
        time_created: '1546880159',
        time_updated: false,
        container_guid: '0',
        owner_guid: '0',
        site_guid: false,
        access_id: '2',
        tags: [],
        nsfw: [],
        nsfw_lock: [],
        allow_comments: false,
        name: 'sammy kay',
        username: 'sammykay',
        language: 'en',
        icontime: '1590613598',
        legacy_guid: false,
        featured_id: false,
        banned: 'no',
        ban_reason: false,
        website: '',
        briefdescription: '',
        gender: '',
        city: '',
        merchant: false,
        boostProPlus: false,
        fb: false,
        mature: 0,
        monetized: '',
        signup_method: false,
        social_profiles: [],
        feature_flags: false,
        programs: [],
        plus: false,
        hashtags: false,
        verified: false,
        founder: false,
        disabled_boost: false,
        boost_autorotate: true,
        categories: [],
        wire_rewards: {
          description: '',
          rewards: {
            points: [],
            money: [],
            tokens: [],
          },
        },
        pinned_posts: ['965386438654205952', '972709142205726720'],
        is_mature: false,
        mature_lock: false,
        last_accepted_tos: 1558597098,
        opted_in_hashtags: 0,
        last_avatar_upload: '0',
        canary: false,
        theme: 'dark',
        toaster_notifications: true,
        mode: 0,
        btc_address: '',
        surge_token: '',
        hide_share_buttons: false,
        allow_unsubscribed_contact: false,
        dismissed_widgets: [],
        urn: 'urn:user:929055781758705675',
        subscribed: false,
        subscriber: false,
        subscribers_count: 5,
        subscriptions_count: 1,
        impressions: 35138,
        boost_rating: 1,
        pro: false,
        pro_published: false,
        rewards: false,
        p2p_media_enabled: false,
        is_admin: false,
        onchain_booster: 0,
        email_confirmed: true,
        eth_wallet: '',
        rating: 1,
        disable_autoplay_videos: false,
        yt_channels: [],
      },
    },
    {
      guid: '809970474896334851',
      owner_guid: '809970474896334851',
      timestamp: null,
      urn: 'urn:user:809970474896334851',
      entity: {
        guid: '809970474896334851',
        type: 'user',
        subtype: false,
        time_created: '1518488009',
        time_updated: false,
        container_guid: '0',
        owner_guid: '0',
        site_guid: false,
        access_id: '2',
        tags: [],
        nsfw: [],
        nsfw_lock: [],
        allow_comments: false,
        name: 'micrbu3825',
        username: 'micrbu3825',
        language: 'en',
        icontime: '1552744086',
        legacy_guid: false,
        featured_id: false,
        banned: 'no',
        ban_reason: false,
        website: '',
        briefdescription: 'Independent blogger',
        gender: '',
        city: 'Nashville',
        merchant: {
          service: 'stripe',
          id: 'acct_1Bz5vgKbfIYNk0xn',
          exclusive: {
            enabled: true,
            amount: 10,
          },
        },
        boostProPlus: false,
        fb: false,
        mature: 1,
        monetized: '',
        signup_method: false,
        social_profiles: [],
        feature_flags: false,
        programs: [],
        plus: false,
        hashtags: false,
        verified: false,
        founder: false,
        disabled_boost: false,
        boost_autorotate: true,
        categories: [
          'animals',
          'music',
          'science',
          'technology',
          'gaming',
          'history',
          'nature',
          'news',
          'politics',
          'spirituality',
        ],
        wire_rewards: null,
        pinned_posts: [],
        is_mature: false,
        mature_lock: false,
        last_accepted_tos: 1558597098,
        opted_in_hashtags: 5,
        last_avatar_upload: '0',
        canary: false,
        theme: 'dark',
        toaster_notifications: true,
        mode: 0,
        btc_address: '',
        surge_token: '',
        hide_share_buttons: false,
        allow_unsubscribed_contact: false,
        dismissed_widgets: ['discovery-disclaimer-2020'],
        chat: true,
        urn: 'urn:user:809970474896334851',
        subscribed: false,
        subscriber: false,
        subscribers_count: 737,
        subscriptions_count: 238,
        impressions: 258388,
        boost_rating: 2,
        pro: false,
        pro_published: false,
        rewards: true,
        p2p_media_enabled: false,
        is_admin: false,
        onchain_booster: 0,
        email_confirmed: true,
        eth_wallet: '0x9C069C91C642110C6A2AAF51D88cfD623165D8bd',
        rating: 1,
        disable_autoplay_videos: false,
        yt_channels: [],
      },
    },
    {
      guid: '746178337646321665',
      owner_guid: '746178337646321665',
      timestamp: null,
      urn: 'urn:user:746178337646321665',
      entity: {
        guid: '746178337646321665',
        type: 'user',
        subtype: false,
        time_created: '1503278779',
        time_updated: false,
        container_guid: '0',
        owner_guid: '0',
        site_guid: false,
        access_id: '2',
        tags: [],
        nsfw: [],
        nsfw_lock: [],
        allow_comments: false,
        name: 'Inquisitor_Firebrand',
        username: 'Inquisitor_Firebrand',
        language: 'en',
        icontime: '1606834216',
        legacy_guid: false,
        featured_id: false,
        banned: 'no',
        ban_reason: false,
        website: '',
        briefdescription:
          'I am not a hooman I am a shrubbery! There are only two genders Chicken and Waffles! Real Life Canon!',
        gender: '',
        city: 'The Moon!',
        merchant: false,
        boostProPlus: false,
        fb: false,
        mature: 0,
        monetized: '',
        signup_method: false,
        social_profiles: [
          {
            key: 'twitch',
            value: 'https://www.twitch.tv/inquisitor_firebrand',
          },
        ],
        feature_flags: false,
        programs: [],
        plus: true,
        hashtags: false,
        verified: false,
        founder: false,
        disabled_boost: false,
        boost_autorotate: false,
        categories: ['gaming', 'history', 'spirituality'],
        wire_rewards: {
          description: '',
          rewards: {
            points: [],
            money: [],
            tokens: [
              {
                amount: '0',
                description:
                  'awkward comments on your posts! \ninappropriate jokes!\nerror!\nnot being on fire!\nuncomfortable flirting!\nhaving eyes! ',
              },
            ],
          },
        },
        pinned_posts: [
          '967575264704815104',
          '967688594077474816',
          '1180899582579793920',
        ],
        is_mature: false,
        mature_lock: false,
        last_accepted_tos: 1558597098,
        opted_in_hashtags: 3,
        last_avatar_upload: '0',
        canary: true,
        theme: 'dark',
        toaster_notifications: true,
        mode: 0,
        btc_address: '',
        surge_token:
          'eyJzZXJ2aWNlIjoiZ29vZ2xlIiwidG9rZW4iOiJmTXdKTFdhMFJmbzpBUEE5MWJFdlhJYWgtMjg1c0JDNkdGYmE2ZlVyYzBDQTJaNjV2ZjJ3WlNURXpYbGdBbEZJV1ZHaHlnbVpSeXJqYndyMXVVWDliMTBqSU5RMktVS0FBbDFpR2tUeW16N2preFJXVExEMFJ3NjdTMElJX2VSOVlNYU1CeGViR2J3bTUtdWNDS0ZGUVVqZCJ9',
        hide_share_buttons: false,
        allow_unsubscribed_contact: false,
        dismissed_widgets: ['discovery-disclaimer-2020'],
        chat: true,
        urn: 'urn:user:746178337646321665',
        subscribed: false,
        subscriber: false,
        subscribers_count: 2090,
        subscriptions_count: 1730,
        impressions: 1497139,
        boost_rating: 2,
        pro: false,
        pro_published: false,
        rewards: true,
        p2p_media_enabled: false,
        is_admin: false,
        onchain_booster: 0,
        email_confirmed: true,
        eth_wallet: '0x1ec28a7b20f245401ccb9b42d93818f83f717577',
        rating: 1,
        disable_autoplay_videos: false,
        yt_channels: [],
      },
    },
    {
      guid: '885604084122394633',
      owner_guid: '885604084122394633',
      timestamp: null,
      urn: 'urn:user:885604084122394633',
      entity: {
        guid: '885604084122394633',
        type: 'user',
        subtype: false,
        time_created: '1536520467',
        time_updated: false,
        container_guid: '0',
        owner_guid: '0',
        site_guid: false,
        access_id: '2',
        tags: ['all', 'blockchain', 'minds', 'comedy', 'gaming', 'memes'],
        nsfw: [],
        nsfw_lock: [],
        allow_comments: false,
        name: 'Darkness to Light',
        username: 'herbpigott',
        language: 'en',
        icontime: '1587590527',
        legacy_guid: false,
        featured_id: false,
        banned: 'no',
        ban_reason: false,
        website: '',
        briefdescription:
          'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor quam eget odio dictum ultricies. Quisque eget dui euismod, elementum quam quis, condimentum ligula. Etiam bibendum, purus dignissim gravida venenatis, nunc velit dictum risus, a sagittis magna ante eget arcu. Nunc vel nunc sit amet justo maximus imperdiet et at nulla. Proin id convallis sem. Aliquam et efficitur ante. Nulla laoreet eu nibh ac hendrerit. Fusce a interdum arcu. Nam luctus porta ligula. Donec orci felis, accumsan id lorem sed, dapibus pellentesque justo. Nam mattis lacus sem. Curabitur velit massa, tempus vel neque ut, efficitur auctor tortor. Mauris nec ipsum eleifend, sagittis est dignissim, ultricies mi. Morbi fermentum nulla lorem, id ultricies ex maximus rutrum.',
        gender: '',
        city: '',
        merchant: false,
        boostProPlus: false,
        fb: false,
        mature: 0,
        monetized: '',
        signup_method: false,
        social_profiles: [],
        feature_flags: false,
        programs: [],
        plus: false,
        hashtags: false,
        verified: false,
        founder: false,
        disabled_boost: false,
        boost_autorotate: true,
        categories: [],
        wire_rewards: {
          description: '',
          rewards: {
            points: [],
            money: [],
            tokens: [],
          },
        },
        pinned_posts: [
          '1162850220710367232',
          '1162848685629546496',
          '1179034803270512640',
        ],
        is_mature: false,
        mature_lock: false,
        last_accepted_tos: 1558597098,
        opted_in_hashtags: 4,
        last_avatar_upload: '0',
        canary: false,
        theme: 'light',
        toaster_notifications: true,
        mode: 0,
        btc_address: '',
        surge_token: '',
        hide_share_buttons: false,
        allow_unsubscribed_contact: false,
        dismissed_widgets: [],
        chat: true,
        urn: 'urn:user:885604084122394633',
        subscribed: false,
        subscriber: false,
        subscribers_count: 2459,
        subscriptions_count: 1506,
        impressions: 5447044,
        boost_rating: 1,
        pro: false,
        pro_published: false,
        rewards: true,
        p2p_media_enabled: false,
        is_admin: false,
        onchain_booster: 0,
        email_confirmed: true,
        eth_wallet: '0xd24e8096373cb69f70794321bbb09189dc65482e',
        rating: 1,
        disable_autoplay_videos: false,
        yt_channels: [],
      },
    },
  ],
};
