const fakeData = {
  wallet: {
    tokens: {
      label: 'Tokens',
      unit: 'tokens',
      balance: 777.123,
      address: null,
    },
    offchain: {
      label: 'Off-chain',
      unit: 'tokens',
      balance: 445.01,
      address: 'offchain',
    },
    onchain: {
      label: 'On-chain',
      unit: 'tokens',
      balance: 333.123,
      address: '0x7bA1A2a94c799f0124B6Bf8481D529BDa844498D',
    },
    receiver: {
      label: 'Receiver',
      unit: 'tokens',
      balance: 0.223,
      address: '0x8aA1A2a94c799f0124B6Bf8481D529BDa844498D',
    },
    cash: {
      label: 'GBP',
      unit: 'gbp',
      balance: 25.5,
      address: null,
    },
    eth: {
      label: 'Ether',
      unit: 'eth',
      balance: 111.159,
      address: '0x7aA1A2a94c799f0124B6Bf8481D529BDa844498D',
    },
    btc: {
      label: 'Bitcoin',
      unit: 'btc',
      balance: 0,
      address: null,
    },
  },
  payout: {
    contributionValues: {
      checkin: 0,
      comments: 0,
      reminds: 0,
      votes: 0,
      subscribers: 0,
      jury_duty: 0,
      onchain_tx: 0,
      referrals: 0,
      referrals_welcome: 0,
    },
    currentReward: '0',
    nextPayout: 0,
    totalNetworkContribution: 78507,
    yourContribution: 0,
    yourRewardFactor: 0,
    yourShare: 0,
    status: 'success',
  },
  visualisation: {
    type: 'chart',
    unit: 'tokens',
    segments: [
      {
        buckets: [
          {
            key: 1567296000000,
            date: '2019-09-01T00:00:00+00:00',
            value: 11,
          },
          {
            key: 1567382400000,
            date: '2019-09-02T00:00:00+00:00',
            value: 12,
          },
          {
            key: 1567468800000,
            date: '2019-09-03T00:00:00+00:00',
            value: 13,
          },
          {
            key: 1567555200000,
            date: '2019-09-04T00:00:00+00:00',
            value: 9,
          },
          {
            key: 1567641600000,
            date: '2019-09-05T00:00:00+00:00',
            value: 1,
          },
          {
            key: 1567296000000,
            date: '2019-09-06T00:00:00+00:00',
            value: 11,
          },
          {
            key: 1567382400000,
            date: '2019-09-07T00:00:00+00:00',
            value: 12,
          },
          {
            key: 1567468800000,
            date: '2019-09-08T00:00:00+00:00',
            value: 13,
          },
          {
            key: 1567555200000,
            date: '2019-09-09T00:00:00+00:00',
            value: 9,
          },
          {
            key: 1567641600000,
            date: '2019-09-10T00:00:00+00:00',
            value: 7,
          },
          {
            key: 1567555200000,
            date: '2019-09-11T00:00:00+00:00',
            value: 9,
          },
          {
            key: 1567641600000,
            date: '2019-09-12T00:00:00+00:00',
            value: 10.2,
          },
        ],
      },
    ],
  },

  ///////////////////////////////////////////////////////////
  stripe_account: {
    status: 'success',
    account: {
      guid: null,
      gender: null,
      firstName: 'Lily',
      lastName: 'Pupper',
      email: null,
      dob: null,
      ssn: null,
      personalIdNumber: null,
      street: 'Borktown',
      city: 'Bork City',
      region: null,
      state: 'CO',
      country: 'US',
      postCode: '80277',
      phoneNumber: null,
      accountNumber: '7778',
      routingNumber: '123455678',
      destination: 'bank',
      status: 'active',
      verified: true,
      bankAccount: {
        id: 'qeorij_823_a0g7',
        object: 'bank_account',
        account: 'acct_9J7sjL08',
        account_holder_name: null,
        account_holder_type: null,
        bank_name: 'BANK OF SNURGLES',
        country: 'US',
        currency: 'gbp',
        default_for_currency: true,
        fingerprint: 'DDEAxPdfOGiWWxw2P',
        last4: '7771',
        metadata: [],
        routing_number: '1212121212',
        status: 'new',
      },
      payoutInterval: 'daily',
      payoutDelay: 2,
      payoutAnchor: null,
      requirement: null,
      totalBalance: {
        amount: 762,
        currency: 'gbp',
      },
      pendingBalance: {
        amount: 142,
        currency: 'gbp',
      },
    },
  },
  ///////////////////////////////////////////////////
  tx_usd: {
    status: 'success',
    transactions: [
      {
        id: 'po_1FSD4tEQcGuFgRfSUgcwjVqm',
        type: 'payout',
        timestamp: 1578977460, // currently 'ts'
        status: 'paid',
        currency: 'gbp',
        net: -158,
      },
      {
        id: 'tr_1FRespEtkBDgTlGKE8yZDxFl',
        type: 'wire',
        timestamp: 1578977458,
        currency: 'gbp',
        net: 80, // currently 'net'
        customer_user: {
          guid: '441939549992521728',
          username: 'sillysealion',
          icontime: '1575402672',
        },
      },
      {
        id: 'tr_1FCuDsEtkBDgTlGK6DhzJH4X',
        type: 'pro_earning',
        timestamp: 1567110480,
        currency: 'gbp',
        net: 80,
        customer_user: {
          guid: '930229554033729554',
          username: 'mindspro',
          icontime: '1543800883',
        },
      },
      {
        id: 'tr_1FKnYSEtkBDgTlGK6K6nK8KU',
        type: 'wire',
        timestamp: 1567110479,
        currency: 'gbp',
        fees: 0,
        net: 78,
        customer_user_guid: null,
        customer_user: {
          guid: '773311697292107790',
          username: 'msantangelo',
          icontime: '1543800883',
        },
      },
      {
        id: 'tr_1FCuDsEtkBDgTlGK6DhzJH4X',
        type: 'pro_earning',
        timestamp: 1567110180,
        gross: 540,
        currency: 'gbp',
        fees: 0,
        net: 80,
        customer_user_guid: null,
        customer_user: {
          guid: '773311697292107790',
          username: 'mindspro',
          icontime: '1543800883',
        },
      },
      {
        id: 'tr_1FCWePEtkBDgTlGKY3EaUqH4',
        type: 'pro_earning',
        timestamp: 1567019869,
        gross: 190,
        currency: 'gbp',
        fees: 0,
        net: 870,
        customer_user_guid: null,
        customer_user: {
          guid: '773311697292107790',
          username: 'mindspro',
          icontime: '1543800883',
        },
      },
      // {
      //   id: 'tr_1F2NvFEtkBDgTlGKqcw7f5Qw',
      //   timestamp: 1564603037,
      //   gross: 100,
      //   currency: 'gbp',
      //   fees: 0,
      //   net: 81,
      //   customer_user_guid: null,
      //   customer_user: null,
      // },
      // {
      //   id: 'tr_1F2Nv0EtkBDgTlGKX6Fn7QQg',
      //   timestamp: 1564603022,
      //   gross: 100,
      //   currency: 'gbp',
      //   fees: 0,
      //   net: 81,
      //   customer_user_guid: null,
      //   customer_user: null,
      // },
      // {
      //   id: 'tr_1EzkSAEtkBDgTlGKlzpytJ6e',
      //   timestamp: 1563974662,
      //   gross: 200,
      //   currency: 'gbp',
      //   fees: 0,
      //   net: 157,
      //   customer_user_guid: null,
      //   customer_user: null,
      // },
      // {
      //   id: 'tr_1EzR67EtkBDgTlGKzxwRK7Kn',
      //   timestamp: 1563900259,
      //   gross: 125,
      //   currency: 'gbp',
      //   fees: 0,
      //   net: 98,
      //   customer_user_guid: null,
      //   customer_user: null,
      // },
      // {
      //   id: 'tr_1EzQs7EtkBDgTlGKOFJEQs05',
      //   timestamp: 1563899391,
      //   gross: 100,
      //   currency: 'gbp',
      //   fees: 0,
      //   net: 79,
      //   customer_user_guid: null,
      //   customer_user: null,
      // },
      // {
      //   id: 'tr_19vo9zEtkBDgTlGKvysqk4rx',
      //   timestamp: 1489153919,
      //   gross: 200,
      //   currency: 'gbp',
      //   fees: 0,
      //   net: 161,
      //   customer_user_guid: null,
      //   customer_user: null,
      // },
    ],
  },

  stripe_payouts: {
    status: 'success',
    transactions: [
      {
        id: 'po_1FSD4tEQcGuFgRfSUgcwjVqm',
        ts: 1570757879,
        status: 'paid',
        refunded: null,
        dispute: null,
        outcome: null,
        currency: 'gbp',
        category: '',
        description: 'STRIPE PAYOUT',
        amount: 1.58,
        // json:....
        account: {
          bank: null,
          last4: null,
        },
      },
      {
        id: 'po_1FFC3IEQcGuFgRfSgPCTlLU1',
        ts: 1567655672,
        status: 'paid',
        refunded: null,
        dispute: null,
        outcome: null,
        currency: 'gbp',
        category: '',
        description: 'STRIPE PAYOUT',
        amount: 9.14,
        // json:....
        account: {
          bank: null,
          last4: null,
        },
      },
    ],
    'load-next': 'po_1FFC3IEQcGuFgRfSgPCTlLU1',
  },
  tx_tokens: {
    status: 'success',
    contract: null,
    transactions: [
      {
        user_guid: 930229554033729554,
        sender: {
          guid: '930229554033729554',
          name: 'omadrid',
          username: 'omadrid',
        },
        receiver: {
          guid: '930229554033729555',
          name: 'omadrid2',
          username: 'omadrid2',
        },
        wallet_address: 'offchain',
        tx: 'oc:1052397161095897106',
        amount: '-1275663706143592000',
        failed: true,
        timestamp: 1576281599,
        contract: 'wire',
        guid: '',
      },
      {
        user_guid: 930229554033729554,
        user: {
          guid: '930229554033729554',
          name: 'omadrid',
          username: 'omadrid',
        },
        wallet_address: 'offchain',
        tx: 'oc:1052397161095897106',
        amount: '125663706143592000',
        failed: false,
        timestamp: 1576281599,
        contract: 'withdraw',
        guid: '',
      },
      {
        user_guid: 930229554033729554,
        user: {
          guid: '930229554033729554',
          name: 'omadrid',
          username: 'omadrid',
        },
        wallet_address: 'offchain',
        tx: 'oc:1052397161095897106',
        amount: '725663706143592000',
        failed: false,
        timestamp: 1576281599,
        contract: 'offchain:boost',
        guid: '',
      },
      {
        user_guid: 930229554033729554,
        user: {
          guid: '930229554033729554',
          type: 'user',
          subtype: false,
          time_created: '1547160008',
          time_updated: false,
          container_guid: '0',
          owner_guid: '0',
          site_guid: false,
          access_id: '2',
          tags: ['Bork'],
          nsfw: [],
          nsfw_lock: [],
          allow_comments: false,
          name: 'omadrid',
          username: 'omadrid',
          language: 'en',
          icontime: '1566340633',
          legacy_guid: false,
          featured_id: false,
          banned: 'no',
          ban_reason: false,
          website: '',
          briefdescription: 'nature//dogs//science',
          dob: '',
          gender: '',
          city: 'Denver',
          merchant: {
            service: 'stripe',
            id: 'acct_1G1NsGK5xlBQ4Xw6',
          },
          boostProPlus: false,
          fb: false,
          mature: 0,
          monetized: '',
          signup_method: false,
          social_profiles: [
            {
              key: 'instagram',
              value: 'https://www.instagram.com/madridoli/',
            },
            {
              key: 'instagram',
              value: 'https://www.instagram.com/your_local_manhole/',
            },
          ],
          feature_flags: false,
          programs: [],
          plus: true,
          hashtags: false,
          verified: false,
          founder: false,
          disabled_boost: false,
          boost_autorotate: false,
          categories: [],
          wire_rewards: {
            description: '',
            rewards: {
              points: [],
              money: [],
              tokens: [],
            },
          },
          pinned_posts: [],
          is_mature: false,
          mature_lock: false,
          last_accepted_tos: 1558597098,
          opted_in_hashtags: -14,
          last_avatar_upload: '0',
          canary: true,
          theme: 'dark',
          toaster_notifications: true,
          mode: 0,
          btc_address: '',
          chat: true,
          urn: 'urn:user:930229554033729554',
          subscribed: false,
          subscriber: false,
          boost_rating: 1,
          pro: true,
          pro_published: false,
          rewards: true,
          p2p_media_enabled: false,
          is_admin: true,
          onchain_booster: 0,
          email_confirmed: true,
          eth_wallet: '0xfeaf4450e5e551e759d990f1ca0d4ad35c37dae9',
          rating: 1,
        },
        wallet_address: 'offchain',
        tx: 'oc:1063608662141968388',
        amount: '-1000000000000000000',
        failed: false,
        timestamp: 1578960065,
        contract: 'offchain:wire',
        sender: {
          guid: '930229554033729554',
          type: 'user',
          subtype: false,
          time_created: '1547160008',
          time_updated: false,
          container_guid: '0',
          owner_guid: '0',
          site_guid: false,
          access_id: '2',
          tags: ['Bork'],
          nsfw: [],
          nsfw_lock: [],
          allow_comments: false,
          name: 'omadrid',
          username: 'omadrid',
          language: 'en',
          icontime: '1566340633',
          legacy_guid: false,
          featured_id: false,
          banned: 'no',
          ban_reason: false,
          website: '',
          briefdescription: 'nature//dogs//science',
          dob: '',
          gender: '',
          city: 'Denver',
          merchant: {
            service: 'stripe',
            id: 'acct_1G1NsGK5xlBQ4Xw6',
          },
          boostProPlus: false,
          fb: false,
          mature: 0,
          monetized: '',
          signup_method: false,
          social_profiles: [
            {
              key: 'instagram',
              value: 'https://www.instagram.com/madridoli/',
            },
            {
              key: 'instagram',
              value: 'https://www.instagram.com/your_local_manhole/',
            },
          ],
          feature_flags: false,
          programs: [],
          plus: true,
          hashtags: false,
          verified: false,
          founder: false,
          disabled_boost: false,
          boost_autorotate: false,
          categories: [],
          wire_rewards: {
            description: '',
            rewards: {
              points: [],
              money: [],
              tokens: [],
            },
          },
          pinned_posts: [],
          is_mature: false,
          mature_lock: false,
          last_accepted_tos: 1558597098,
          opted_in_hashtags: -14,
          last_avatar_upload: '0',
          canary: true,
          theme: 'dark',
          toaster_notifications: true,
          mode: 0,
          btc_address: '',
          chat: true,
          urn: 'urn:user:930229554033729554',
          subscribed: false,
          subscriber: false,
          boost_rating: 1,
          pro: true,
          pro_published: false,
          rewards: true,
          p2p_media_enabled: false,
          is_admin: true,
          onchain_booster: 0,
          email_confirmed: true,
          eth_wallet: '0xfeaf4450e5e551e759d990f1ca0d4ad35c37dae9',
          rating: 1,
        },
        receiver: {
          guid: '996936419819659279',
          type: 'user',
          subtype: false,
          time_created: '1563064164',
          time_updated: false,
          container_guid: '0',
          owner_guid: '0',
          site_guid: false,
          access_id: '2',
          tags: [],
          nsfw: [],
          nsfw_lock: [],
          allow_comments: false,
          name: 'lilyisadog',
          username: 'lilyisadog',
          language: 'en',
          icontime: '1576264393',
          legacy_guid: false,
          featured_id: false,
          banned: 'no',
          ban_reason: false,
          website: '',
          briefdescription: '',
          dob: '',
          gender: '',
          city: '',
          merchant: {
            service: 'stripe',
            id: 'acct_1FpJp0JHesO0VKX5',
          },
          boostProPlus: false,
          fb: false,
          mature: 0,
          monetized: '',
          signup_method: false,
          social_profiles: [],
          feature_flags: false,
          programs: [],
          plus: false,
          hashtags: false,
          verified: false,
          founder: false,
          disabled_boost: false,
          boost_autorotate: true,
          categories: [],
          wire_rewards: null,
          pinned_posts: [],
          is_mature: false,
          mature_lock: false,
          last_accepted_tos: 1558597098,
          opted_in_hashtags: 0,
          last_avatar_upload: '1566327695',
          canary: true,
          theme: false,
          toaster_notifications: true,
          mode: 0,
          btc_address: '',
          urn: 'urn:user:996936419819659279',
          subscribed: true,
          subscriber: false,
          boost_rating: 1,
          pro: false,
          pro_published: false,
          rewards: true,
          p2p_media_enabled: false,
          is_admin: false,
          onchain_booster: 0,
          email_confirmed: true,
          eth_wallet: '0xfeaf4450e5e551e759d990f1ca0d4ad35c37dae9',
          rating: 1,
        },
        guid: '',
      },
      {
        user_guid: 930229554033729554,
        user: {
          guid: '930229554033729554',
          type: 'user',
          subtype: false,
          time_created: '1547160008',
          time_updated: false,
          container_guid: '0',
          owner_guid: '0',
          site_guid: false,
          access_id: '2',
          tags: ['Bork'],
          nsfw: [],
          nsfw_lock: [],
          allow_comments: false,
          name: 'omadrid',
          username: 'omadrid',
          language: 'en',
          icontime: '1566340633',
          legacy_guid: false,
          featured_id: false,
          banned: 'no',
          ban_reason: false,
          website: '',
          briefdescription: 'nature//dogs//science',
          dob: '',
          gender: '',
          city: 'Denver',
          merchant: {
            service: 'stripe',
            id: 'acct_1G1NsGK5xlBQ4Xw6',
          },
          boostProPlus: false,
          fb: false,
          mature: 0,
          monetized: '',
          signup_method: false,
          social_profiles: [
            {
              key: 'instagram',
              value: 'https://www.instagram.com/madridoli/',
            },
            {
              key: 'instagram',
              value: 'https://www.instagram.com/your_local_manhole/',
            },
          ],
          feature_flags: false,
          programs: [],
          plus: true,
          hashtags: false,
          verified: false,
          founder: false,
          disabled_boost: false,
          boost_autorotate: false,
          categories: [],
          wire_rewards: {
            description: '',
            rewards: {
              points: [],
              money: [],
              tokens: [],
            },
          },
          pinned_posts: [],
          is_mature: false,
          mature_lock: false,
          last_accepted_tos: 1558597098,
          opted_in_hashtags: -14,
          last_avatar_upload: '0',
          canary: true,
          theme: 'dark',
          toaster_notifications: true,
          mode: 0,
          btc_address: '',
          chat: true,
          urn: 'urn:user:930229554033729554',
          subscribed: false,
          subscriber: false,
          boost_rating: 1,
          pro: true,
          pro_published: false,
          rewards: true,
          p2p_media_enabled: false,
          is_admin: true,
          onchain_booster: 0,
          email_confirmed: true,
          eth_wallet: '0xfeaf4450e5e551e759d990f1ca0d4ad35c37dae9',
          rating: 1,
        },
        wallet_address: 'offchain',
        tx: 'oc:1052397161095897106',
        amount: '125663706143592000',
        failed: false,
        timestamp: 1576281599,
        contract: 'offchain:reward',
        guid: '',
      },
      {
        user_guid: 930229554033729554,
        user: {
          guid: '930229554033729554',
          type: 'user',
          subtype: false,
          time_created: '1547160008',
          time_updated: false,
          container_guid: '0',
          owner_guid: '0',
          site_guid: false,
          access_id: '2',
          tags: ['Bork'],
          nsfw: [],
          nsfw_lock: [],
          allow_comments: false,
          name: 'omadrid',
          username: 'omadrid',
          language: 'en',
          icontime: '1566340633',
          legacy_guid: false,
          featured_id: false,
          banned: 'no',
          ban_reason: false,
          website: '',
          briefdescription: 'nature//dogs//science',
          dob: '',
          gender: '',
          city: 'Denver',
          merchant: {
            service: 'stripe',
            id: 'acct_1G1NsGK5xlBQ4Xw6',
          },
          boostProPlus: false,
          fb: false,
          mature: 0,
          monetized: '',
          signup_method: false,
          social_profiles: [
            {
              key: 'instagram',
              value: 'https://www.instagram.com/madridoli/',
            },
            {
              key: 'instagram',
              value: 'https://www.instagram.com/your_local_manhole/',
            },
          ],
          feature_flags: false,
          programs: [],
          plus: true,
          hashtags: false,
          verified: false,
          founder: false,
          disabled_boost: false,
          boost_autorotate: false,
          categories: [],
          wire_rewards: {
            description: '',
            rewards: {
              points: [],
              money: [],
              tokens: [],
            },
          },
          pinned_posts: [],
          is_mature: false,
          mature_lock: false,
          last_accepted_tos: 1558597098,
          opted_in_hashtags: -14,
          last_avatar_upload: '0',
          canary: true,
          theme: 'dark',
          toaster_notifications: true,
          mode: 0,
          btc_address: '',
          chat: true,
          urn: 'urn:user:930229554033729554',
          subscribed: false,
          subscriber: false,
          boost_rating: 1,
          pro: true,
          pro_published: false,
          rewards: true,
          p2p_media_enabled: false,
          is_admin: true,
          onchain_booster: 0,
          email_confirmed: true,
          eth_wallet: '0xfeaf4450e5e551e759d990f1ca0d4ad35c37dae9',
          rating: 1,
        },
        wallet_address: 'offchain',
        tx: 'oc:1052304512816627713',
        amount: '-1000000000000000000',
        failed: false,
        timestamp: 1576264946,
        contract: 'offchain:wire',
        sender: {
          guid: '930229554033729554',
          type: 'user',
          subtype: false,
          time_created: '1547160008',
          time_updated: false,
          container_guid: '0',
          owner_guid: '0',
          site_guid: false,
          access_id: '2',
          tags: ['Bork'],
          nsfw: [],
          nsfw_lock: [],
          allow_comments: false,
          name: 'omadrid',
          username: 'omadrid',
          language: 'en',
          icontime: '1566340633',
          legacy_guid: false,
          featured_id: false,
          banned: 'no',
          ban_reason: false,
          website: '',
          briefdescription: 'nature//dogs//science',
          dob: '',
          gender: '',
          city: 'Denver',
          merchant: {
            service: 'stripe',
            id: 'acct_1G1NsGK5xlBQ4Xw6',
          },
          boostProPlus: false,
          fb: false,
          mature: 0,
          monetized: '',
          signup_method: false,
          social_profiles: [
            {
              key: 'instagram',
              value: 'https://www.instagram.com/madridoli/',
            },
            {
              key: 'instagram',
              value: 'https://www.instagram.com/your_local_manhole/',
            },
          ],
          feature_flags: false,
          programs: [],
          plus: true,
          hashtags: false,
          verified: false,
          founder: false,
          disabled_boost: false,
          boost_autorotate: false,
          categories: [],
          wire_rewards: {
            description: '',
            rewards: {
              points: [],
              money: [],
              tokens: [],
            },
          },
          pinned_posts: [],
          is_mature: false,
          mature_lock: false,
          last_accepted_tos: 1558597098,
          opted_in_hashtags: -14,
          last_avatar_upload: '0',
          canary: true,
          theme: 'dark',
          toaster_notifications: true,
          mode: 0,
          btc_address: '',
          chat: true,
          urn: 'urn:user:930229554033729554',
          subscribed: false,
          subscriber: false,
          boost_rating: 1,
          pro: true,
          pro_published: false,
          rewards: true,
          p2p_media_enabled: false,
          is_admin: true,
          onchain_booster: 0,
          email_confirmed: true,
          eth_wallet: '0xfeaf4450e5e551e759d990f1ca0d4ad35c37dae9',
          rating: 1,
        },
        receiver: {
          guid: '996936419819659279',
          type: 'user',
          subtype: false,
          time_created: '1563064164',
          time_updated: false,
          container_guid: '0',
          owner_guid: '0',
          site_guid: false,
          access_id: '2',
          tags: [],
          nsfw: [],
          nsfw_lock: [],
          allow_comments: false,
          name: 'lilyisadog',
          username: 'lilyisadog',
          language: 'en',
          icontime: '1576264393',
          legacy_guid: false,
          featured_id: false,
          banned: 'no',
          ban_reason: false,
          website: '',
          briefdescription: '',
          dob: '',
          gender: '',
          city: '',
          merchant: {
            service: 'stripe',
            id: 'acct_1FpJp0JHesO0VKX5',
          },
          boostProPlus: false,
          fb: false,
          mature: 0,
          monetized: '',
          signup_method: false,
          social_profiles: [],
          feature_flags: false,
          programs: [],
          plus: false,
          hashtags: false,
          verified: false,
          founder: false,
          disabled_boost: false,
          boost_autorotate: true,
          categories: [],
          wire_rewards: null,
          pinned_posts: [],
          is_mature: false,
          mature_lock: false,
          last_accepted_tos: 1558597098,
          opted_in_hashtags: 0,
          last_avatar_upload: '1566327695',
          canary: true,
          theme: false,
          toaster_notifications: true,
          mode: 0,
          btc_address: '',
          urn: 'urn:user:996936419819659279',
          subscribed: true,
          subscriber: false,
          boost_rating: 1,
          pro: false,
          pro_published: false,
          rewards: true,
          p2p_media_enabled: false,
          is_admin: false,
          onchain_booster: 0,
          email_confirmed: true,
          eth_wallet: '0xfeaf4450e5e551e759d990f1ca0d4ad35c37dae9',
          rating: 1,
        },
        guid: '',
      },
      {
        user_guid: 930229554033729554,
        user: {
          guid: '930229554033729554',
          type: 'user',
          subtype: false,
          time_created: '1547160008',
          time_updated: false,
          container_guid: '0',
          owner_guid: '0',
          site_guid: false,
          access_id: '2',
          tags: ['Bork'],
          nsfw: [],
          nsfw_lock: [],
          allow_comments: false,
          name: 'omadrid',
          username: 'omadrid',
          language: 'en',
          icontime: '1566340633',
          legacy_guid: false,
          featured_id: false,
          banned: 'no',
          ban_reason: false,
          website: '',
          briefdescription: 'nature//dogs//science',
          dob: '',
          gender: '',
          city: 'Denver',
          merchant: {
            service: 'stripe',
            id: 'acct_1G1NsGK5xlBQ4Xw6',
          },
          boostProPlus: false,
          fb: false,
          mature: 0,
          monetized: '',
          signup_method: false,
          social_profiles: [
            {
              key: 'instagram',
              value: 'https://www.instagram.com/madridoli/',
            },
            {
              key: 'instagram',
              value: 'https://www.instagram.com/your_local_manhole/',
            },
          ],
          feature_flags: false,
          programs: [],
          plus: true,
          hashtags: false,
          verified: false,
          founder: false,
          disabled_boost: false,
          boost_autorotate: false,
          categories: [],
          wire_rewards: {
            description: '',
            rewards: {
              points: [],
              money: [],
              tokens: [],
            },
          },
          pinned_posts: [],
          is_mature: false,
          mature_lock: false,
          last_accepted_tos: 1558597098,
          opted_in_hashtags: -14,
          last_avatar_upload: '0',
          canary: true,
          theme: 'dark',
          toaster_notifications: true,
          mode: 0,
          btc_address: '',
          chat: true,
          urn: 'urn:user:930229554033729554',
          subscribed: false,
          subscriber: false,
          boost_rating: 1,
          pro: true,
          pro_published: false,
          rewards: true,
          p2p_media_enabled: false,
          is_admin: true,
          onchain_booster: 0,
          email_confirmed: true,
          eth_wallet: '0xfeaf4450e5e551e759d990f1ca0d4ad35c37dae9',
          rating: 1,
        },
        wallet_address: 'offchain',
        tx: 'oc:1052303678548590593',
        amount: '-1000000000000000000',
        failed: false,
        timestamp: 1576264747,
        contract: 'offchain:wire',
        sender: {
          guid: '930229554033729554',
          type: 'user',
          subtype: false,
          time_created: '1547160008',
          time_updated: false,
          container_guid: '0',
          owner_guid: '0',
          site_guid: false,
          access_id: '2',
          tags: ['Bork'],
          nsfw: [],
          nsfw_lock: [],
          allow_comments: false,
          name: 'omadrid',
          username: 'omadrid',
          language: 'en',
          icontime: '1566340633',
          legacy_guid: false,
          featured_id: false,
          banned: 'no',
          ban_reason: false,
          website: '',
          briefdescription: 'nature//dogs//science',
          dob: '',
          gender: '',
          city: 'Denver',
          merchant: {
            service: 'stripe',
            id: 'acct_1G1NsGK5xlBQ4Xw6',
          },
          boostProPlus: false,
          fb: false,
          mature: 0,
          monetized: '',
          signup_method: false,
          social_profiles: [
            {
              key: 'instagram',
              value: 'https://www.instagram.com/madridoli/',
            },
            {
              key: 'instagram',
              value: 'https://www.instagram.com/your_local_manhole/',
            },
          ],
          feature_flags: false,
          programs: [],
          plus: true,
          hashtags: false,
          verified: false,
          founder: false,
          disabled_boost: false,
          boost_autorotate: false,
          categories: [],
          wire_rewards: {
            description: '',
            rewards: {
              points: [],
              money: [],
              tokens: [],
            },
          },
          pinned_posts: [],
          is_mature: false,
          mature_lock: false,
          last_accepted_tos: 1558597098,
          opted_in_hashtags: -14,
          last_avatar_upload: '0',
          canary: true,
          theme: 'dark',
          toaster_notifications: true,
          mode: 0,
          btc_address: '',
          chat: true,
          urn: 'urn:user:930229554033729554',
          subscribed: false,
          subscriber: false,
          boost_rating: 1,
          pro: true,
          pro_published: false,
          rewards: true,
          p2p_media_enabled: false,
          is_admin: true,
          onchain_booster: 0,
          email_confirmed: true,
          eth_wallet: '0xfeaf4450e5e551e759d990f1ca0d4ad35c37dae9',
          rating: 1,
        },
        receiver: {
          guid: '996936419819659279',
          type: 'user',
          subtype: false,
          time_created: '1563064164',
          time_updated: false,
          container_guid: '0',
          owner_guid: '0',
          site_guid: false,
          access_id: '2',
          tags: [],
          nsfw: [],
          nsfw_lock: [],
          allow_comments: false,
          name: 'lilyisadog',
          username: 'lilyisadog',
          language: 'en',
          icontime: '1576264393',
          legacy_guid: false,
          featured_id: false,
          banned: 'no',
          ban_reason: false,
          website: '',
          briefdescription: '',
          dob: '',
          gender: '',
          city: '',
          merchant: {
            service: 'stripe',
            id: 'acct_1FpJp0JHesO0VKX5',
          },
          boostProPlus: false,
          fb: false,
          mature: 0,
          monetized: '',
          signup_method: false,
          social_profiles: [],
          feature_flags: false,
          programs: [],
          plus: false,
          hashtags: false,
          verified: false,
          founder: false,
          disabled_boost: false,
          boost_autorotate: true,
          categories: [],
          wire_rewards: null,
          pinned_posts: [],
          is_mature: false,
          mature_lock: false,
          last_accepted_tos: 1558597098,
          opted_in_hashtags: 0,
          last_avatar_upload: '1566327695',
          canary: true,
          theme: false,
          toaster_notifications: true,
          mode: 0,
          btc_address: '',
          urn: 'urn:user:996936419819659279',
          subscribed: true,
          subscriber: false,
          boost_rating: 1,
          pro: false,
          pro_published: false,
          rewards: true,
          p2p_media_enabled: false,
          is_admin: false,
          onchain_booster: 0,
          email_confirmed: true,
          eth_wallet: '0xfeaf4450e5e551e759d990f1ca0d4ad35c37dae9',
          rating: 1,
        },
        guid: '',
      },
      {
        user_guid: 930229554033729554,
        user: {
          guid: '930229554033729554',
          type: 'user',
          subtype: false,
          time_created: '1547160008',
          time_updated: false,
          container_guid: '0',
          owner_guid: '0',
          site_guid: false,
          access_id: '2',
          tags: ['Bork'],
          nsfw: [],
          nsfw_lock: [],
          allow_comments: false,
          name: 'omadrid',
          username: 'omadrid',
          language: 'en',
          icontime: '1566340633',
          legacy_guid: false,
          featured_id: false,
          banned: 'no',
          ban_reason: false,
          website: '',
          briefdescription: 'nature//dogs//science',
          dob: '',
          gender: '',
          city: 'Denver',
          merchant: {
            service: 'stripe',
            id: 'acct_1G1NsGK5xlBQ4Xw6',
          },
          boostProPlus: false,
          fb: false,
          mature: 0,
          monetized: '',
          signup_method: false,
          social_profiles: [
            {
              key: 'instagram',
              value: 'https://www.instagram.com/madridoli/',
            },
            {
              key: 'instagram',
              value: 'https://www.instagram.com/your_local_manhole/',
            },
          ],
          feature_flags: false,
          programs: [],
          plus: true,
          hashtags: false,
          verified: false,
          founder: false,
          disabled_boost: false,
          boost_autorotate: false,
          categories: [],
          wire_rewards: {
            description: '',
            rewards: {
              points: [],
              money: [],
              tokens: [],
            },
          },
          pinned_posts: [],
          is_mature: false,
          mature_lock: false,
          last_accepted_tos: 1558597098,
          opted_in_hashtags: -14,
          last_avatar_upload: '0',
          canary: true,
          theme: 'dark',
          toaster_notifications: true,
          mode: 0,
          btc_address: '',
          chat: true,
          urn: 'urn:user:930229554033729554',
          subscribed: false,
          subscriber: false,
          boost_rating: 1,
          pro: true,
          pro_published: false,
          rewards: true,
          p2p_media_enabled: false,
          is_admin: true,
          onchain_booster: 0,
          email_confirmed: true,
          eth_wallet: '0xfeaf4450e5e551e759d990f1ca0d4ad35c37dae9',
          rating: 1,
        },
        wallet_address: 'offchain',
        tx: 'oc:1049860429410476040',
        amount: '15707963267949000',
        failed: false,
        timestamp: 1575676799,
        contract: 'offchain:reward',
        guid: '',
      },
      {
        user_guid: 930229554033729554,
        user: {
          guid: '930229554033729554',
          type: 'user',
          subtype: false,
          time_created: '1547160008',
          time_updated: false,
          container_guid: '0',
          owner_guid: '0',
          site_guid: false,
          access_id: '2',
          tags: ['Bork'],
          nsfw: [],
          nsfw_lock: [],
          allow_comments: false,
          name: 'omadrid',
          username: 'omadrid',
          language: 'en',
          icontime: '1566340633',
          legacy_guid: false,
          featured_id: false,
          banned: 'no',
          ban_reason: false,
          website: '',
          briefdescription: 'nature//dogs//science',
          dob: '',
          gender: '',
          city: 'Denver',
          merchant: {
            service: 'stripe',
            id: 'acct_1G1NsGK5xlBQ4Xw6',
          },
          boostProPlus: false,
          fb: false,
          mature: 0,
          monetized: '',
          signup_method: false,
          social_profiles: [
            {
              key: 'instagram',
              value: 'https://www.instagram.com/madridoli/',
            },
            {
              key: 'instagram',
              value: 'https://www.instagram.com/your_local_manhole/',
            },
          ],
          feature_flags: false,
          programs: [],
          plus: true,
          hashtags: false,
          verified: false,
          founder: false,
          disabled_boost: false,
          boost_autorotate: false,
          categories: [],
          wire_rewards: {
            description: '',
            rewards: {
              points: [],
              money: [],
              tokens: [],
            },
          },
          pinned_posts: [],
          is_mature: false,
          mature_lock: false,
          last_accepted_tos: 1558597098,
          opted_in_hashtags: -14,
          last_avatar_upload: '0',
          canary: true,
          theme: 'dark',
          toaster_notifications: true,
          mode: 0,
          btc_address: '',
          chat: true,
          urn: 'urn:user:930229554033729554',
          subscribed: false,
          subscriber: false,
          boost_rating: 1,
          pro: true,
          pro_published: false,
          rewards: true,
          p2p_media_enabled: false,
          is_admin: true,
          onchain_booster: 0,
          email_confirmed: true,
          eth_wallet: '0xfeaf4450e5e551e759d990f1ca0d4ad35c37dae9',
          rating: 1,
        },
        wallet_address: 'offchain',
        tx: 'oc:1048364721213808659',
        amount: '-1777000000000000000',
        failed: false,
        timestamp: 1575325627,
        contract: 'offchain:withdraw',
        guid: '',
      },
      {
        user_guid: 930229554033729554,
        user: {
          guid: '930229554033729554',
          type: 'user',
          subtype: false,
          time_created: '1547160008',
          time_updated: false,
          container_guid: '0',
          owner_guid: '0',
          site_guid: false,
          access_id: '2',
          tags: ['Bork'],
          nsfw: [],
          nsfw_lock: [],
          allow_comments: false,
          name: 'omadrid',
          username: 'omadrid',
          language: 'en',
          icontime: '1566340633',
          legacy_guid: false,
          featured_id: false,
          banned: 'no',
          ban_reason: false,
          website: '',
          briefdescription: 'nature//dogs//science',
          dob: '',
          gender: '',
          city: 'Denver',
          merchant: {
            service: 'stripe',
            id: 'acct_1G1NsGK5xlBQ4Xw6',
          },
          boostProPlus: false,
          fb: false,
          mature: 0,
          monetized: '',
          signup_method: false,
          social_profiles: [
            {
              key: 'instagram',
              value: 'https://www.instagram.com/madridoli/',
            },
            {
              key: 'instagram',
              value: 'https://www.instagram.com/your_local_manhole/',
            },
          ],
          feature_flags: false,
          programs: [],
          plus: true,
          hashtags: false,
          verified: false,
          founder: false,
          disabled_boost: false,
          boost_autorotate: false,
          categories: [],
          wire_rewards: {
            description: '',
            rewards: {
              points: [],
              money: [],
              tokens: [],
            },
          },
          pinned_posts: [],
          is_mature: false,
          mature_lock: false,
          last_accepted_tos: 1558597098,
          opted_in_hashtags: -14,
          last_avatar_upload: '0',
          canary: true,
          theme: 'dark',
          toaster_notifications: true,
          mode: 0,
          btc_address: '',
          chat: true,
          urn: 'urn:user:930229554033729554',
          subscribed: false,
          subscriber: false,
          boost_rating: 1,
          pro: true,
          pro_published: false,
          rewards: true,
          p2p_media_enabled: false,
          is_admin: true,
          onchain_booster: 0,
          email_confirmed: true,
          eth_wallet: '0xfeaf4450e5e551e759d990f1ca0d4ad35c37dae9',
          rating: 1,
        },
        wallet_address: '0xfeaf4450e5e551e759d990f1ca0d4ad35c37dae9',
        tx:
          '0xda6f4a81cd116057fcb1568af46754cc5346057edb16bfbd748f3223927d4906',
        amount: '1777000000000000000',
        failed: false,
        timestamp: 1575325597,
        contract: 'withdraw',
        guid: '',
      },
      {
        user_guid: 930229554033729554,
        user: {
          guid: '930229554033729554',
          type: 'user',
          subtype: false,
          time_created: '1547160008',
          time_updated: false,
          container_guid: '0',
          owner_guid: '0',
          site_guid: false,
          access_id: '2',
          tags: ['Bork'],
          nsfw: [],
          nsfw_lock: [],
          allow_comments: false,
          name: 'omadrid',
          username: 'omadrid',
          language: 'en',
          icontime: '1566340633',
          legacy_guid: false,
          featured_id: false,
          banned: 'no',
          ban_reason: false,
          website: '',
          briefdescription: 'nature//dogs//science',
          dob: '',
          gender: '',
          city: 'Denver',
          merchant: {
            service: 'stripe',
            id: 'acct_1G1NsGK5xlBQ4Xw6',
          },
          boostProPlus: false,
          fb: false,
          mature: 0,
          monetized: '',
          signup_method: false,
          social_profiles: [
            {
              key: 'instagram',
              value: 'https://www.instagram.com/madridoli/',
            },
            {
              key: 'instagram',
              value: 'https://www.instagram.com/your_local_manhole/',
            },
          ],
          feature_flags: false,
          programs: [],
          plus: true,
          hashtags: false,
          verified: false,
          founder: false,
          disabled_boost: false,
          boost_autorotate: false,
          categories: [],
          wire_rewards: {
            description: '',
            rewards: {
              points: [],
              money: [],
              tokens: [],
            },
          },
          pinned_posts: [],
          is_mature: false,
          mature_lock: false,
          last_accepted_tos: 1558597098,
          opted_in_hashtags: -14,
          last_avatar_upload: '0',
          canary: true,
          theme: 'dark',
          toaster_notifications: true,
          mode: 0,
          btc_address: '',
          chat: true,
          urn: 'urn:user:930229554033729554',
          subscribed: false,
          subscriber: false,
          boost_rating: 1,
          pro: true,
          pro_published: false,
          rewards: true,
          p2p_media_enabled: false,
          is_admin: true,
          onchain_booster: 0,
          email_confirmed: true,
          eth_wallet: '0xfeaf4450e5e551e759d990f1ca0d4ad35c37dae9',
          rating: 1,
        },
        wallet_address: 'offchain',
        tx: 'oc:1042250308194934797',
        amount: '94247779607694000',
        failed: false,
        timestamp: 1573862399,
        contract: 'offchain:reward',
        guid: '',
      },
      {
        user_guid: 930229554033729554,
        user: {
          guid: '930229554033729554',
          type: 'user',
          subtype: false,
          time_created: '1547160008',
          time_updated: false,
          container_guid: '0',
          owner_guid: '0',
          site_guid: false,
          access_id: '2',
          tags: ['Bork'],
          nsfw: [],
          nsfw_lock: [],
          allow_comments: false,
          name: 'omadrid',
          username: 'omadrid',
          language: 'en',
          icontime: '1566340633',
          legacy_guid: false,
          featured_id: false,
          banned: 'no',
          ban_reason: false,
          website: '',
          briefdescription: 'nature//dogs//science',
          dob: '',
          gender: '',
          city: 'Denver',
          merchant: {
            service: 'stripe',
            id: 'acct_1G1NsGK5xlBQ4Xw6',
          },
          boostProPlus: false,
          fb: false,
          mature: 0,
          monetized: '',
          signup_method: false,
          social_profiles: [
            {
              key: 'instagram',
              value: 'https://www.instagram.com/madridoli/',
            },
            {
              key: 'instagram',
              value: 'https://www.instagram.com/your_local_manhole/',
            },
          ],
          feature_flags: false,
          programs: [],
          plus: true,
          hashtags: false,
          verified: false,
          founder: false,
          disabled_boost: false,
          boost_autorotate: false,
          categories: [],
          wire_rewards: {
            description: '',
            rewards: {
              points: [],
              money: [],
              tokens: [],
            },
          },
          pinned_posts: [],
          is_mature: false,
          mature_lock: false,
          last_accepted_tos: 1558597098,
          opted_in_hashtags: -14,
          last_avatar_upload: '0',
          canary: true,
          theme: 'dark',
          toaster_notifications: true,
          mode: 0,
          btc_address: '',
          chat: true,
          urn: 'urn:user:930229554033729554',
          subscribed: false,
          subscriber: false,
          boost_rating: 1,
          pro: true,
          pro_published: false,
          rewards: true,
          p2p_media_enabled: false,
          is_admin: true,
          onchain_booster: 0,
          email_confirmed: true,
          eth_wallet: '0xfeaf4450e5e551e759d990f1ca0d4ad35c37dae9',
          rating: 1,
        },
        wallet_address: 'offchain',
        tx: 'oc:1030292533927747588',
        amount: '31415926535898000',
        failed: false,
        timestamp: 1571011199,
        contract: 'offchain:reward',
        guid: '',
      },
      {
        user_guid: 930229554033729554,
        user: {
          guid: '930229554033729554',
          type: 'user',
          subtype: false,
          time_created: '1547160008',
          time_updated: false,
          container_guid: '0',
          owner_guid: '0',
          site_guid: false,
          access_id: '2',
          tags: ['Bork'],
          nsfw: [],
          nsfw_lock: [],
          allow_comments: false,
          name: 'omadrid',
          username: 'omadrid',
          language: 'en',
          icontime: '1566340633',
          legacy_guid: false,
          featured_id: false,
          banned: 'no',
          ban_reason: false,
          website: '',
          briefdescription: 'nature//dogs//science',
          dob: '',
          gender: '',
          city: 'Denver',
          merchant: {
            service: 'stripe',
            id: 'acct_1G1NsGK5xlBQ4Xw6',
          },
          boostProPlus: false,
          fb: false,
          mature: 0,
          monetized: '',
          signup_method: false,
          social_profiles: [
            {
              key: 'instagram',
              value: 'https://www.instagram.com/madridoli/',
            },
            {
              key: 'instagram',
              value: 'https://www.instagram.com/your_local_manhole/',
            },
          ],
          feature_flags: false,
          programs: [],
          plus: true,
          hashtags: false,
          verified: false,
          founder: false,
          disabled_boost: false,
          boost_autorotate: false,
          categories: [],
          wire_rewards: {
            description: '',
            rewards: {
              points: [],
              money: [],
              tokens: [],
            },
          },
          pinned_posts: [],
          is_mature: false,
          mature_lock: false,
          last_accepted_tos: 1558597098,
          opted_in_hashtags: -14,
          last_avatar_upload: '0',
          canary: true,
          theme: 'dark',
          toaster_notifications: true,
          mode: 0,
          btc_address: '',
          chat: true,
          urn: 'urn:user:930229554033729554',
          subscribed: false,
          subscriber: false,
          boost_rating: 1,
          pro: true,
          pro_published: false,
          rewards: true,
          p2p_media_enabled: false,
          is_admin: true,
          onchain_booster: 0,
          email_confirmed: true,
          eth_wallet: '0xfeaf4450e5e551e759d990f1ca0d4ad35c37dae9',
          rating: 1,
        },
        wallet_address: 'offchain',
        tx: 'oc:1029204390726082576',
        amount: '282743338823082000',
        failed: false,
        timestamp: 1570751999,
        contract: 'offchain:reward',
        guid: '',
      },
      {
        user_guid: 930229554033729554,
        user: {
          guid: '930229554033729554',
          type: 'user',
          subtype: false,
          time_created: '1547160008',
          time_updated: false,
          container_guid: '0',
          owner_guid: '0',
          site_guid: false,
          access_id: '2',
          tags: ['Bork'],
          nsfw: [],
          nsfw_lock: [],
          allow_comments: false,
          name: 'omadrid',
          username: 'omadrid',
          language: 'en',
          icontime: '1566340633',
          legacy_guid: false,
          featured_id: false,
          banned: 'no',
          ban_reason: false,
          website: '',
          briefdescription: 'nature//dogs//science',
          dob: '',
          gender: '',
          city: 'Denver',
          merchant: {
            service: 'stripe',
            id: 'acct_1G1NsGK5xlBQ4Xw6',
          },
          boostProPlus: false,
          fb: false,
          mature: 0,
          monetized: '',
          signup_method: false,
          social_profiles: [
            {
              key: 'instagram',
              value: 'https://www.instagram.com/madridoli/',
            },
            {
              key: 'instagram',
              value: 'https://www.instagram.com/your_local_manhole/',
            },
          ],
          feature_flags: false,
          programs: [],
          plus: true,
          hashtags: false,
          verified: false,
          founder: false,
          disabled_boost: false,
          boost_autorotate: false,
          categories: [],
          wire_rewards: {
            description: '',
            rewards: {
              points: [],
              money: [],
              tokens: [],
            },
          },
          pinned_posts: [],
          is_mature: false,
          mature_lock: false,
          last_accepted_tos: 1558597098,
          opted_in_hashtags: -14,
          last_avatar_upload: '0',
          canary: true,
          theme: 'dark',
          toaster_notifications: true,
          mode: 0,
          btc_address: '',
          chat: true,
          urn: 'urn:user:930229554033729554',
          subscribed: false,
          subscriber: false,
          boost_rating: 1,
          pro: true,
          pro_published: false,
          rewards: true,
          p2p_media_enabled: false,
          is_admin: true,
          onchain_booster: 0,
          email_confirmed: true,
          eth_wallet: '0xfeaf4450e5e551e759d990f1ca0d4ad35c37dae9',
          rating: 1,
        },
        wallet_address: 'offchain',
        tx: 'oc:1027392442741039121',
        amount: '31415926535898000',
        failed: false,
        timestamp: 1570319999,
        contract: 'offchain:reward',
        guid: '',
      },
      {
        user_guid: 930229554033729554,
        user: {
          guid: '930229554033729554',
          type: 'user',
          subtype: false,
          time_created: '1547160008',
          time_updated: false,
          container_guid: '0',
          owner_guid: '0',
          site_guid: false,
          access_id: '2',
          tags: ['Bork'],
          nsfw: [],
          nsfw_lock: [],
          allow_comments: false,
          name: 'omadrid',
          username: 'omadrid',
          language: 'en',
          icontime: '1566340633',
          legacy_guid: false,
          featured_id: false,
          banned: 'no',
          ban_reason: false,
          website: '',
          briefdescription: 'nature//dogs//science',
          dob: '',
          gender: '',
          city: 'Denver',
          merchant: {
            service: 'stripe',
            id: 'acct_1G1NsGK5xlBQ4Xw6',
          },
          boostProPlus: false,
          fb: false,
          mature: 0,
          monetized: '',
          signup_method: false,
          social_profiles: [
            {
              key: 'instagram',
              value: 'https://www.instagram.com/madridoli/',
            },
            {
              key: 'instagram',
              value: 'https://www.instagram.com/your_local_manhole/',
            },
          ],
          feature_flags: false,
          programs: [],
          plus: true,
          hashtags: false,
          verified: false,
          founder: false,
          disabled_boost: false,
          boost_autorotate: false,
          categories: [],
          wire_rewards: {
            description: '',
            rewards: {
              points: [],
              money: [],
              tokens: [],
            },
          },
          pinned_posts: [],
          is_mature: false,
          mature_lock: false,
          last_accepted_tos: 1558597098,
          opted_in_hashtags: -14,
          last_avatar_upload: '0',
          canary: true,
          theme: 'dark',
          toaster_notifications: true,
          mode: 0,
          btc_address: '',
          chat: true,
          urn: 'urn:user:930229554033729554',
          subscribed: false,
          subscriber: false,
          boost_rating: 1,
          pro: true,
          pro_published: false,
          rewards: true,
          p2p_media_enabled: false,
          is_admin: true,
          onchain_booster: 0,
          email_confirmed: true,
          eth_wallet: '0xfeaf4450e5e551e759d990f1ca0d4ad35c37dae9',
          rating: 1,
        },
        wallet_address: 'offchain',
        tx: 'oc:1026667648009642002',
        amount: '157079632679490000',
        failed: false,
        timestamp: 1570147199,
        contract: 'offchain:reward',
        guid: '',
      },
    ],
    'load-next':
      'ACoACAAAAW2UEOgYCG9mZmNoYWluFm9jOjEwMjY2Njc2NDgwMDk2NDIwMDLwf///8/B////z',
  },
  tx_tokens_filtered: {
    status: 'success',
    contract: null,
    transactions: [
      {
        user_guid: 930229554033729554,
        user: {
          guid: '930229554033729554',
          type: 'user',
          subtype: false,
          time_created: '1547160008',
          time_updated: false,
          container_guid: '0',
          owner_guid: '0',
          site_guid: false,
          access_id: '2',
          tags: ['Bork'],
          nsfw: [],
          nsfw_lock: [],
          allow_comments: false,
          name: 'omadrid',
          username: 'omadrid',
          language: 'en',
          icontime: '1566340633',
          legacy_guid: false,
          featured_id: false,
          banned: 'no',
          ban_reason: false,
          website: '',
          briefdescription: 'nature//dogs//science',
          dob: '',
          gender: '',
          city: 'Denver',
          merchant: {
            service: 'stripe',
            id: 'acct_1G1NsGK5xlBQ4Xw6',
          },
          boostProPlus: false,
          fb: false,
          mature: 0,
          monetized: '',
          signup_method: false,
          social_profiles: [
            {
              key: 'instagram',
              value: 'https://www.instagram.com/madridoli/',
            },
            {
              key: 'instagram',
              value: 'https://www.instagram.com/your_local_manhole/',
            },
          ],
          feature_flags: false,
          programs: [],
          plus: true,
          hashtags: false,
          verified: false,
          founder: false,
          disabled_boost: false,
          boost_autorotate: false,
          categories: [],
          wire_rewards: {
            description: '',
            rewards: {
              points: [],
              money: [],
              tokens: [],
            },
          },
          pinned_posts: [],
          is_mature: false,
          mature_lock: false,
          last_accepted_tos: 1558597098,
          opted_in_hashtags: -14,
          last_avatar_upload: '0',
          canary: true,
          theme: 'dark',
          toaster_notifications: true,
          mode: 0,
          btc_address: '',
          chat: true,
          urn: 'urn:user:930229554033729554',
          subscribed: false,
          subscriber: false,
          boost_rating: 1,
          pro: true,
          pro_published: false,
          rewards: true,
          p2p_media_enabled: false,
          is_admin: true,
          onchain_booster: 0,
          email_confirmed: true,
          eth_wallet: '0xfeaf4450e5e551e759d990f1ca0d4ad35c37dae9',
          rating: 1,
        },
        wallet_address: 'offchain',
        tx: 'oc:1026667648009642002',
        amount: '157079632679490000',
        failed: false,
        timestamp: 1570147199,
        contract: 'offchain:reward',
        guid: '',
      },
    ],
    'load-next':
      'ACoACAAAAW2UEOgYCG9mZmNoYWluFm9jOjEwMjY2Njc2NDgwMDk2NDIwMDLwf///8/B////z',
  },
  pendingTokenRewards: {
    status: 'success',
    contributions: [
      {
        amount: 2,
        metrics: {
          checkins: {
            amount: '1',
            metric: 'checkins',
            score: 2,
            timestamp: 1573776000000,
            user: '930229554033729554',
          },
          votes: {
            amount: '1',
            metric: 'votes',
            score: 1,
            timestamp: 1573776000000,
            user: '930229554033729554',
          },
        },
        score: 3,
        share: 0.0025391236637861718,
        timestamp: 1573776000000,
      },
    ],
  },
  token_chart: {
    status: 'success',
    dashboard: {
      category: 'engagement',
      label: 'Engagement',
      description: '',
      timespan: '30d',
      timespans: [
        // {
        //   id: 'today',
        //   label: 'Today',
        //   interval: 'day',
        //   selected: false,
        //   comparison_interval: 1,
        //   from_ts_ms: 1579824000000,
        //   from_ts_iso: '2020-01-24T00:00:00+00:00',
        // },
        {
          id: '1m',
          label: '1M',
          interval: 'day',
          selected: true,
          comparison_interval: 30,
          from_ts_ms: 1577232000000,
          from_ts_iso: '2019-12-25T00:00:00+00:00',
        },
        {
          id: '3m',
          label: '3M',
          interval: 'day',
          selected: false,
          comparison_interval: 90,
          from_ts_ms: 1577232000000,
          from_ts_iso: '2019-12-25T00:00:00+00:00',
        },
        {
          id: '1y',
          label: '1Y',
          interval: 'month',
          selected: false,
          comparison_interval: 365,
          from_ts_ms: 1548288000000,
          from_ts_iso: '2019-01-24T00:00:00+00:00',
        },
        {
          id: 'max',
          label: 'Max',
          interval: 'day', // not sure... kinda depends on how long max is for the user
          selected: false,
          comparison_interval: 30,
          from_ts_ms: 1577836800000,
          from_ts_iso: '2020-01-01T00:00:00+00:00',
        },
      ],
      metric: 'token_balance',
      metrics: [
        {
          id: 'token_balance',
          label: 'Token Balance',
          description: 'Token Balance',
          unit: 'number',
          permissions: ['admin', 'user'],
          summary: {
            current_value: 0,
            comparison_value: 0,
            comparison_interval: 30,
            comparison_positive_inclination: true,
          },
          visualisation: {
            type: 'chart',
            segments: [
              {
                label: null,
                comparison: false,
                buckets: [
                  {
                    key: 1577404800000,
                    date: '2019-12-27T00:00:00+00:00',
                    value: 3151.371452017148,
                  },
                  {
                    key: 1577491200000,
                    date: '2019-12-28T00:00:00+00:00',
                    value: 3151.292912200808,
                  },
                  {
                    key: 1577577600000,
                    date: '2019-12-29T00:00:00+00:00',
                    value: 3151.2614962742723,
                  },
                  {
                    key: 1577664000000,
                    date: '2019-12-30T00:00:00+00:00',
                    value: 3151.1829564579325,
                  },
                  {
                    key: 1577836800000,
                    date: '2020-01-01T00:00:00+00:00',
                    value: 3151.025876825253,
                  },
                  {
                    key: 1577923200000,
                    date: '2020-01-02T00:00:00+00:00',
                    value: 3152.8687971925733,
                  },
                  {
                    key: 1578009600000,
                    date: '2020-01-03T00:00:00+00:00',
                    value: 3152.7117175598937,
                  },
                  {
                    key: 1578268800000,
                    date: '2020-01-06T00:00:00+00:00',
                    value: 3152.58605385375,
                  },
                  {
                    key: 1578355200000,
                    date: '2020-01-07T00:00:00+00:00',
                    value: 3152.381850331267,
                  },
                  {
                    key: 1578441600000,
                    date: '2020-01-08T00:00:00+00:00',
                    value: 3152.319018478195,
                  },
                  {
                    key: 1578614400000,
                    date: '2020-01-10T00:00:00+00:00',
                    value: 3152.1933547720514,
                  },
                  {
                    key: 1578787200000,
                    date: '2020-01-12T00:00:00+00:00',
                    value: 3162.1933547720514,
                  },
                  {
                    key: 1578873600000,
                    date: '2020-01-13T00:00:00+00:00',
                    value: 3162.05198310264,
                  },
                  {
                    key: 1578960000000,
                    date: '2020-01-14T00:00:00+00:00',
                    value: 3161.7378238372808,
                  },
                  {
                    key: 1579046400000,
                    date: '2020-01-15T00:00:00+00:00',
                    value: 3161.612160131137,
                  },
                  {
                    key: 1579132800000,
                    date: '2020-01-16T00:00:00+00:00',
                    value: 3161.486496424993,
                  },
                  {
                    key: 1579219200000,
                    date: '2020-01-17T00:00:00+00:00',
                    value: 3161.3922486453857,
                  },
                  {
                    key: 1579305600000,
                    date: '2020-01-18T00:00:00+00:00',
                    value: 3161.3765406821176,
                  },
                  {
                    key: 1579392000000,
                    date: '2020-01-19T00:00:00+00:00',
                    value: 3161.1723371596345,
                  },
                  {
                    key: 1579478400000,
                    date: '2020-01-20T00:00:00+00:00',
                    value: 3160.936717710615,
                  },
                  {
                    key: 1579651200000,
                    date: '2020-01-22T00:00:00+00:00',
                    value: 3180.716806224864,
                  },
                  {
                    key: 1579824000000,
                    date: '2020-01-24T00:00:00+00:00',
                    value: 3180.616806224864,
                  },
                ],
              },
            ],
          },
        },
      ],
      filter: ['platform::all', 'view_type::total', 'channel::all'],
      filters: [],
    },
  },
};

export default fakeData;
