const fakeData = {
  wallet: {
    tokens: {
      label: 'Tokens',
      unit: 'tokens',
      balance: 777.123,
      address: null,
    },
    offchain: {
      label: 'Off-chain',
      unit: 'tokens',
      balance: 445.01,
      address: 'offchain',
    },
    onchain: {
      label: 'On-chain',
      unit: 'tokens',
      balance: 333.123,
      address: '0x7bA1A2a94c799f0124B6Bf8481D529BDa844498D',
    },
    receiver: {
      label: 'Receiver',
      unit: 'tokens',
      balance: 0.223,
      address: '0x8aA1A2a94c799f0124B6Bf8481D529BDa844498D',
    },
    usd: {
      label: 'USD',
      unit: 'usd',
      balance: 25.5,
      address: null,
    },
    eth: {
      label: 'Ether',
      unit: 'eth',
      balance: 111.159,
      address: '0x7aA1A2a94c799f0124B6Bf8481D529BDa844498D',
    },
    btc: {
      label: 'Bitcoin',
      unit: 'btc',
      balance: 0,
      address: null,
    },
  },
  payout: {
    contributionValues: {
      checkin: 0,
      comments: 0,
      reminds: 0,
      votes: 0,
      subscribers: 0,
      jury_duty: 0,
      onchain_tx: 0,
      referrals: 0,
      referrals_welcome: 0,
    },
    currentReward: '0',
    nextPayout: 0,
    totalNetworkContribution: 78507,
    yourContribution: 0,
    yourRewardFactor: 0,
    yourShare: 0,
    status: 'success',
  },
  visualisation: {
    type: 'chart',
    unit: 'tokens',
    segments: [
      {
        buckets: [
          {
            key: 1567296000000,
            date: '2019-09-01T00:00:00+00:00',
            value: 11,
          },
          {
            key: 1567382400000,
            date: '2019-09-02T00:00:00+00:00',
            value: 12,
          },
          {
            key: 1567468800000,
            date: '2019-09-03T00:00:00+00:00',
            value: 13,
          },
          {
            key: 1567555200000,
            date: '2019-09-04T00:00:00+00:00',
            value: 9,
          },
          {
            key: 1567641600000,
            date: '2019-09-05T00:00:00+00:00',
            value: 1,
          },
          {
            key: 1567296000000,
            date: '2019-09-06T00:00:00+00:00',
            value: 11,
          },
          {
            key: 1567382400000,
            date: '2019-09-07T00:00:00+00:00',
            value: 12,
          },
          {
            key: 1567468800000,
            date: '2019-09-08T00:00:00+00:00',
            value: 13,
          },
          {
            key: 1567555200000,
            date: '2019-09-09T00:00:00+00:00',
            value: 9,
          },
          {
            key: 1567641600000,
            date: '2019-09-10T00:00:00+00:00',
            value: 7,
          },
          {
            key: 1567555200000,
            date: '2019-09-11T00:00:00+00:00',
            value: 9,
          },
          {
            key: 1567641600000,
            date: '2019-09-12T00:00:00+00:00',
            value: 10.2,
          },
        ],
      },
    ],
  },
  token_transactions: {
    filters: [
      {
        id: 'transaction_types',
        label: 'Transaction Types',
        options: [
          {
            id: 'all',
            label: 'All',
            selected: true,
          },
          {
            id: 'offchain_wire',
            label: 'Off-Chain Wire',
            selected: false,
          },
          {
            id: 'onchain_wire',
            label: 'On-Chain Wire',
            selected: false,
          },
          {
            id: 'rewards',
            label: 'Rewards',
            selected: false,
          },
          {
            id: 'purchases',
            label: 'Purchases',
            selected: false,
          },
          {
            id: 'boost',
            label: 'Boost',
            selected: false,
          },
          {
            id: 'onchain_transfer',
            label: 'On-Chain Transfer',
            selected: false,
          },
        ],
      },
    ],
    pending: {
      total_points: 7,
      contributions: [
        { id: 'checkins', label: 'Check-ins', occurrences: 1, points: 2 },
        { id: 'comments', label: 'Comments', occurrences: 2, points: 4 },
        { id: 'votes', label: 'Votes', occurrences: 1, points: 1 },
      ],
    },
    days: [
      {
        ts_ms: 1567296000000, // today's date
        transactions: [
          {
            ts_ms: 1567296000090, // time of tx
            type_id: 'boosts',
            type_label: 'Boosts',
            diff: -5.0,
            running_total: 25.0,
          },
          {
            ts_ms: 1567296000080,
            type_id: 'rewards',
            type_label: 'Rewards',
            diff: 0.4,
            running_total: 30.0,
            details: {
              total_points: 10,
              contributions: [
                {
                  id: 'checkins',
                  label: 'Check-ins',
                  occurrences: 4,
                  points: 8,
                },
                {
                  id: 'comments',
                  label: 'Comments',
                  occurrences: 1,
                  points: 2,
                },
              ],
            },
          },
          {
            ts_ms: 1567296000070,
            type_id: 'wires',
            type_label: 'Wires', // make sure we have the label field bc this eventually needs to change to 'Pay'
            diff: -1.5,
            running_total: 29.6,
            subtype_id: 'offchain_wires_outbound',
            entity: {
              user_guid: 123,
              username: 'my_wire_recipient',
              //...etc...
            },
          },
          {
            ts_ms: 1567296000060,
            type_id: 'wires',
            type_label: 'Wires',
            diff: 2.0,
            running_total: 30.1,
            subtype_id: 'offchain_wires_inbound',
            entity: {
              user_guid: 456,
              username: 'whoever_wired_me',
              //...etc...
            },
          },
        ],
      },
      {
        ts_ms: 1567295000000, // yesterday's date
        transactions: [
          {
            ts_ms: 1567295000090,
            type_id: 'purchases',
            type_label: 'Purchases',
            diff: -10.0,
            running_total: 28.1,
            subtype_id: 'minds_pro_membership',
          },
          {
            ts_ms: 1567295000080,
            type_id: 'rewards',
            type_label: 'Rewards',
            diff: 0.9,
            running_total: 38.1,
            details: {
              total_points: 50,
              contributions: [
                {
                  id: 'jury_duty',
                  label: 'Jury Duty',
                  occurrences: 2,
                  points: 50,
                },
              ],
            },
          },
        ],
      },
      // days go on...
    ],
    load_next: '',
    status: 'success',
  },
  ///////////////////////////////////////////////////////////
  tx_usd: {
    status: 'success',
    transactions: [
      {
        id: 'tr_1FRespEtkBDgTlGKE8yZDxFl',
        timestamp: 1578977458, // testing jan 13th 1570626435,
        gross: 100,
        currency: 'gbp',
        fees: 0,
        net: 80,
        customer_user_guid: null,
        customer_user: {
          guid: '441939549992521728',
          type: 'user',
          subtype: false,
          time_created: '1430742599',
          time_updated: false,
          container_guid: '0',
          owner_guid: '0',
          site_guid: false,
          access_id: '2',
          tags: [],
          nsfw: [5],
          nsfw_lock: [5],
          allow_comments: false,
          name: 'Sillysealion',
          username: 'sillysealion',
          language: 'en',
          icontime: '1575402672',
          legacy_guid: false,
          featured_id: false,
          banned: 'no',
          ban_reason: 'Infringes my copyright',
          website: '',
          briefdescription: 'going to the moon',
          dob: '',
          gender: '',
          city: 'London',
          merchant: {
            service: 'stripe',
            id: 'acct_1FCq2jAKSYLZgYJH',
          },
          boostProPlus: false,
          fb: false,
          mature: 0,
          monetized: '',
          signup_method: false,
          social_profiles: [],
          feature_flags: false,
          programs: ['affiliate'],
          plus: false,
          hashtags: false,
          verified: true,
          founder: true,
          disabled_boost: false,
          boost_autorotate: true,
          categories: [],
          wire_rewards: {
            description: '',
            rewards: {
              points: [],
              money: [],
              tokens: [],
            },
          },
          pinned_posts: [],
          is_mature: false,
          mature_lock: false,
          last_accepted_tos: 1558597098,
          opted_in_hashtags: 6,
          last_avatar_upload: '1560844120',
          canary: true,
          theme: 'light',
          toaster_notifications: true,
          mode: 2,
          btc_address: '1ztwe1gh1',
          chat: true,
          urn: 'urn:user:441939549992521728',
          subscribed: false,
          subscriber: true,
          boost_rating: 1,
          pro: false,
          pro_published: false,
          rewards: true,
          p2p_media_enabled: false,
          is_admin: false,
          onchain_booster: 0,
          eth_wallet: '0x177fd9efd24535e73b81e99e7f838cdef265e6cb',
          rating: 2,
        },
      },
      {
        id: 'tr_1FKnYSEtkBDgTlGK6K6nK8KU',
        timestamp: 1568991472,
        gross: 100,
        currency: 'gbp',
        fees: 0,
        net: 78,
        customer_user_guid: null,
        customer_user: {
          guid: '773311697292107790',
          type: 'user',
          subtype: false,
          time_created: '1509747876',
          time_updated: false,
          container_guid: '0',
          owner_guid: '0',
          site_guid: false,
          access_id: '2',
          tags: [],
          nsfw: [],
          nsfw_lock: [],
          allow_comments: false,
          name: 'Martin Santangelo',
          username: 'msantangelo',
          language: 'en',
          icontime: '1543800883',
          legacy_guid: false,
          featured_id: false,
          banned: 'no',
          ban_reason: false,
          website: '',
          briefdescription: 'Full Stack Developer at @minds',
          dob: '',
          gender: '',
          city: 'Parana',
          merchant: false,
          boostProPlus: false,
          fb: false,
          mature: 0,
          monetized: '',
          signup_method: false,
          social_profiles: [
            {
              key: 'twitter',
              value: 'https://twitter.com/msantang78',
            },
            {
              key: 'facebook',
              value: 'https://www.facebook.com/martinalejandro.santangelo',
            },
          ],
          feature_flags: false,
          programs: [],
          plus: true,
          hashtags: false,
          verified: true,
          founder: false,
          disabled_boost: false,
          boost_autorotate: true,
          categories: ['science', 'technology', 'news', 'film'],
          wire_rewards: null,
          pinned_posts: [],
          is_mature: false,
          mature_lock: false,
          last_accepted_tos: 1558597098,
          opted_in_hashtags: 6,
          last_avatar_upload: '0',
          canary: true,
          theme: 'light',
          toaster_notifications: true,
          mode: 0,
          btc_address: '',
          chat: true,
          urn: 'urn:user:773311697292107790',
          subscribed: true,
          subscriber: true,
          boost_rating: 2,
          pro: true,
          pro_published: false,
          rewards: true,
          p2p_media_enabled: false,
          is_admin: false,
          onchain_booster: 0,
          eth_wallet: '0x8fbf96D53F781ACC297D9b5C363fe4291be32Ad6',
          rating: 1,
        },
      },
      {
        id: 'tr_1FCuDsEtkBDgTlGK6DhzJH4X',
        timestamp: 1567110480,
        gross: 100,
        currency: 'gbp',
        fees: 0,
        net: 80,
        customer_user_guid: null,
        customer_user: null,
      },
      {
        id: 'tr_1FCuDsEtkBDgTlGK6DhzJH4X',
        timestamp: 1567110180,
        gross: 540,
        currency: 'gbp',
        fees: 0,
        net: 80,
        customer_user_guid: null,
        customer_user: null,
      },
      {
        id: 'tr_1FCWePEtkBDgTlGKY3EaUqH4',
        timestamp: 1567019869,
        gross: 100,
        currency: 'gbp',
        fees: 0,
        net: 80,
        customer_user_guid: null,
        customer_user: null,
      },
      {
        id: 'tr_1F2NvFEtkBDgTlGKqcw7f5Qw',
        timestamp: 1564603037,
        gross: 100,
        currency: 'gbp',
        fees: 0,
        net: 81,
        customer_user_guid: null,
        customer_user: null,
      },
      {
        id: 'tr_1F2Nv0EtkBDgTlGKX6Fn7QQg',
        timestamp: 1564603022,
        gross: 100,
        currency: 'gbp',
        fees: 0,
        net: 81,
        customer_user_guid: null,
        customer_user: null,
      },
      {
        id: 'tr_1EzkSAEtkBDgTlGKlzpytJ6e',
        timestamp: 1563974662,
        gross: 200,
        currency: 'gbp',
        fees: 0,
        net: 157,
        customer_user_guid: null,
        customer_user: null,
      },
      {
        id: 'tr_1EzR67EtkBDgTlGKzxwRK7Kn',
        timestamp: 1563900259,
        gross: 125,
        currency: 'gbp',
        fees: 0,
        net: 98,
        customer_user_guid: null,
        customer_user: null,
      },
      {
        id: 'tr_1EzQs7EtkBDgTlGKOFJEQs05',
        timestamp: 1563899391,
        gross: 100,
        currency: 'gbp',
        fees: 0,
        net: 79,
        customer_user_guid: null,
        customer_user: null,
      },
      {
        id: 'tr_19vo9zEtkBDgTlGKvysqk4rx',
        timestamp: 1489153919,
        gross: 200,
        currency: 'gbp',
        fees: 0,
        net: 161,
        customer_user_guid: null,
        customer_user: null,
      },
    ],
  },
  stripe_account: {
    status: 'success',
    account: {
      guid: null,
      gender: null,
      firstName: 'Lily',
      lastName: 'Pupper',
      email: null,
      dob: null,
      ssn: null,
      personalIdNumber: null,
      street: 'Borktown',
      city: 'Bork City',
      region: null,
      state: 'CO',
      country: 'US',
      postCode: '80277',
      phoneNumber: null,
      accountNumber: '7778',
      routingNumber: '123455678',
      destination: 'bank',
      status: 'active',
      verified: true,
      bankAccount: {
        id: 'qeorij_823_a0g7',
        object: 'bank_account',
        account: 'acct_9J7sjL08',
        account_holder_name: null,
        account_holder_type: null,
        bank_name: 'BANK OF SNURGLES',
        country: 'US',
        currency: 'usd',
        default_for_currency: true,
        fingerprint: 'DDEAxPdfOGiWWxw2P',
        last4: '7771',
        metadata: [],
        routing_number: '1212121212',
        status: 'new',
      },
      payoutInterval: 'daily',
      payoutDelay: 2,
      payoutAnchor: null,
      requirement: null,
      totalBalance: {
        amount: 7628,
        currency: 'usd',
      },
      pendingBalance: {
        amount: 1420,
        currency: 'usd',
      },
    },
  },
  stripe_payouts: {
    status: 'success',
    transactions: [
      {
        id: 'po_1FSD4tEQcGuFgRfSUgcwjVqm',
        ts: 1570757879,
        status: 'paid',
        refunded: null,
        dispute: null,
        outcome: null,
        currency: 'gbp',
        category: '',
        description: 'STRIPE PAYOUT',
        amount: 1.58,
        json:
          '{"id":"po_1FSD4tEQcGuFgRfSUgcwjVqm","object":"payout","amount":158,"arrival_date":1571184000,"automatic":true,"balance_transaction":"txn_1FSD4tEQcGuFgRfSe0Xitjxp","created":1570757879,"currency":"gbp","description":"STRIPE PAYOUT","destination":"ba_19QgKZEQcGuFgRfSIt76kMsR","failure_balance_transaction":null,"failure_code":null,"failure_message":null,"livemode":true,"metadata":[],"method":"standard","source_type":"card","statement_descriptor":"MINDS","status":"paid","type":"bank_account"}',
        account: {
          bank: null,
          last4: null,
        },
      },
      {
        id: 'po_1FFC3IEQcGuFgRfSgPCTlLU1',
        ts: 1567655672,
        status: 'paid',
        refunded: null,
        dispute: null,
        outcome: null,
        currency: 'gbp',
        category: '',
        description: 'STRIPE PAYOUT',
        amount: 9.14,
        json:
          '{"id":"po_1FFC3IEQcGuFgRfSgPCTlLU1","object":"payout","amount":914,"arrival_date":1568073600,"automatic":true,"balance_transaction":"txn_1FFC3IEQcGuFgRfSHWhDxEke","created":1567655672,"currency":"gbp","description":"STRIPE PAYOUT","destination":"ba_19QgKZEQcGuFgRfSIt76kMsR","failure_balance_transaction":null,"failure_code":null,"failure_message":null,"livemode":true,"metadata":[],"method":"standard","source_type":"card","statement_descriptor":"MINDS","status":"paid","type":"bank_account"}',
        account: {
          bank: null,
          last4: null,
        },
      },
    ],
    'load-next': 'po_1FFC3IEQcGuFgRfSgPCTlLU1',
  },
};
export default fakeData;
