export enum Flags {
  APPOINT_ADMIN = 'appoint_admin',
  APPOINT_MODERATOR = 'appoint_moderator',
  APPROVE_SUBSCRIBER = 'approve_subscriber',
  CREATE_CHANNEL = 'create_channel',
  CREATE_COMMENT = 'create_comment',
  CREATE_GROUP = 'create_group',
  CREATE_POST = 'create_post',
  DELETE_CHANNEL = 'delete_channel',
  DELETE_COMMENT = 'delete_comment',
  DELETE_GROUP = 'delete_group',
  DELETE_POST = 'delete_post',
  EDIT_CHANNEL = 'edit_channel',
  EDIT_COMMENT = 'edit_comment',
  EDIT_GROUP = 'edit_group',
  EDIT_POST = 'edit_post',
  INVITE = 'invite',
  JOIN = 'join',
  JOIN_GATHERING = 'gathering',
  MESSAGE = 'message',
  SUBSCRIBE = 'subscribe',
  TAG = 'tag',
  REMIND = 'remind',
  VIEW = 'view',
  VOTE = 'vote',
}
