#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# sh .githooks/pre-commit && npx -y pretty-quick@2.0.2 --staged --bail --pattern "**/*.*(ts|html|scss)"
sh .githooks/pre-commit && npx --no-install pretty-quick --staged --bail --pattern "**/*.*(ts|html|scss)"
